.github/workflows/main.yaml, .gitignore, composer.json, composer.lock, docs/index.rst, monorepo-builder.php
To ensure we keep things working, add some validation on the repository structure.
=> [FEATURE] Add monorepo validation setup

.github/workflows/main.yaml, .gitignore, .php-cs-fixer.dist.php, composer.json, composer.lock, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/DependencyInjection/Typo3DocsThemeExtension.php, packages/typo3-docs-theme/src/Directives/ConfvalDirective.php, packages/typo3-docs-theme/src/Directives/GroupTabDirective.php, packages/typo3-docs-theme/src/Directives/T3FieldListTableDirective.php, packages/typo3-docs-theme/src/Directives/TabsDirective.php, packages/typo3-docs-theme/src/Nodes/GroupTabNode.php
I think we should also run this in the Github Actions but I am not sure how
=> [TASK] Introduce TYPO3 CS for PHP

index.php
This was still here from my early trials of getting docker up and running
=> [FEATURE] Delete leftover file

.gitignore, .php-cs-fixer.dist.php, README.rst, composer.json
This makes clear it does not contain information about the project but test-data
=> [TASK] Rename "Documentation" folder to fixtures-local

.github/workflows/docker.yaml
Set the docker image to lower case when executing the meta step.
=> [TASK] Set docker image name to lower

.github/workflows/main.yaml, .gitignore, .php-cs-fixer.dist.php, composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon
Put existings errors in the baseline for now, they can be analyzed and solved in a follow up
=> [FEATURE] Introduce PHP stan

.github/workflows/phar.yaml, .gitignore, bin/guides, box.json, composer.json, composer.lock, docs/index.rst, tools/.gitignore, tools/build-phar.sh
This adds a script to build a phar file from this repository.
Some extra scripting is required due a limitation in box regaring
composer plugins. The rest is just plain box building.
=> [TASK] build phar

.github/workflows/main.yaml, .gitignore, composer.json, composer.lock, phpunit.xml.dist, tests/ApplicationTestCase.php, tests/Integration/IntegrationTest.php, tests/Integration/tests/index/expected/index.html, tests/Integration/tests/index/expected/objects.inv.json, tests/Integration/tests/index/input/index.rst
=> [FEATURE] Introduce integration tests

composer.json, guides.xml, packages/typo3-guides-extension/composer.json, packages/typo3-guides-extension/resources/config/typo3-guides.php, packages/typo3-guides-extension/src/Command/RunDecorator.php, packages/typo3-guides-extension/src/DependencyInjection/Typo3GuidesExtension.php, phpstan.neon
By decorating the run command we can add extra functionality to the default command of guides. In this case I added the input guessing logic to find the correct input format or single file readme documentation.
=> [FEATURE] Add automated input detection

composer.lock
the Markdowns support is better now and the :options: directive available
=> [TAKS] Update phpdocumentor/guides

packages/typo3-docs-theme/resources/template/structure/layout.html.twig, tests/Integration/tests/index/expected/index.html
Versions are loaded via javascript, we just need to render the current version.
=> [FEATURE] Add version switch to template

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/TextRoles/IssueReferenceTextRole.php, tests/Integration/tests/role-issue-invalid/expected/index.html, tests/Integration/tests/role-issue-invalid/expected/logs/warning.log, tests/Integration/tests/role-issue-invalid/input/index.rst, tests/Integration/tests/role-issue/expected/index.html, tests/Integration/tests/role-issue/input/index.rst
This directive is used in the changelog and other places to link to forge.
=> [FEATURE] Implement ":issues:" directive

tests/Integration/tests/bootstrap-cards/expected/index.html, tests/Integration/tests/bootstrap-cards/input/index.rst
We currently do it like this: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Content/Cards.html Though in future I would like to introduce a directive for that.
=> [TASK] Add tests for bootstrap cards

Makefile
=> [TASK] Use project's container when running compose for pre-commit-tests

composer.json, composer.lock, guides.xml, packages/typo3-docs-theme/resources/template/structure/singledocument.html.twig, packages/typo3-docs-theme/resources/template/structure/singlepage.html.twig, packages/typo3-guides-extension/resources/config/typo3-guides.php, packages/typo3-guides-extension/src/Renderer/NodeRenderer/SinglePageDocumentRenderer.php, packages/typo3-guides-extension/src/Renderer/SinglePageRenderer.php, tests/Integration/IntegrationTest.php, tests/Integration/tests/singlepage/expected/index.html, tests/Integration/tests/singlepage/input/guides.xml, tests/Integration/tests/singlepage/input/index.rst, tests/Integration/tests/singlepage/input/sub/index.rst
This introduces a single page output format
=> [FEATURE] single page renderer

packages/php-domain/resources/config/php-domain.php, tests/Integration/tests/php/interface-namespace-directive/expected/index.html
Message to self: Always register directives in DI
=> [BUGFIX] Make namespace directive work correctly.

packages/typo3-guides-extension/src/Renderer/SinglePageRenderer.php, tests/Integration/tests/singlepage/expected/singlehtml/Index.html, tests/Integration/tests/singlepage/input/sub/index.rst
This prevents overwriting a "Index.html" file.
Resolves: #78
=> [BUGFIX] Creates distinct SinglePage index file (singlepage-index.html)

composer.lock, packages/typo3-docs-theme/resources/template/body/code.html.twig
This also resolves a bug with the code-block directive concerning line numbers.
Related: https://github.com/phpDocumentor/guides/issues/684
=> [TASK] Update phpdocumentor/guides packages

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/resources/template/structure/document.html.twig, packages/typo3-docs-theme/resources/template/structure/layout.html.twig, packages/typo3-docs-theme/src/Nodes/PageLinkNode.php, packages/typo3-docs-theme/src/Twig/TwigExtension.php, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/next-prev/input/index.rst, tests/Integration/tests-full/next-prev/input/page.rst, tests/Integration/tests-full/next-prev/input/yetAnotherPage.rst, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/page-with-subpages/input/guides.xml, tests/Integration/tests-full/page-with-subpages/input/index.rst, tests/Integration/tests-full/page-with-subpages/input/sub/index.rst
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/35
=> [FEATURE] Prev/Next links

tests/Integration/tests-full/page-with-subpages/input/guides.xml
This probably broke due merging without rebasing
=> [BUGFIX] Fix xml linting

tools/integration-test-baseline.php
The integration-baseline script also shortened HTML files in the directory tests-full where the full files should be kept
Additionally do not copy .log files
=> [BUGFIX] Do not shorten full integration tests

action.yml, composer.json, composer.lock
Allow the workflows to use the new working-dir option
=> [FEATURE] add working dir option

composer.json, composer.lock, packages/typo3-docs-theme/resources/template/structure/layout.html.twig, packages/typo3-guides-extension/composer.json, packages/typo3-guides-extension/src/DependencyInjection/TestExtension.php, tests/ApplicationTestCase.php, tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/sitemap/expected/Sitemap.html, tests/Integration/tests-full/sitemap/expected/index.html
And mock it in the integration tests so that integration tests are still possible
=> [FEATURE] Output Last rendered date

guides.xml
It should be located in Documentation/guides.xml not in the main guides
=> [TASK] Remove superfluous interlink inventory

action.yml, composer.lock, entrypoint.sh
To be able to debug the github actions add SHELL_VERBOSITY environment variable
Upgraded guides to have this new option.
=> [TASK] Add debug output

composer.lock
Directive php:class is available now
=> [TASK] Update PHP-domain

composer.lock, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, tests/Integration/tests/code-block/with-language-aliases/expected/index.html, tests/Integration/tests/code-block/with-language-aliases/input/index.rst, tests/Integration/tests/code-block/with-unavailable-language/expected/logs/warning.log, tests/Integration/tests/code-block/with-unavailable-language/input/index.rst
Additionally, add an integration test for logging an unavailable language.
=> [FEATURE] Add language aliases for code highlighting

packages/typo3-docs-theme/resources/template/structure/layout.html.twig, tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/sitemap/expected/Sitemap.html, tests/Integration/tests-full/sitemap/expected/index.html, tests/Integration/tests-full/two-toctrees/expected/index.html
Allows to easily differentiate between sphinx and phpdocumentor
=> [TASK] Add `generator` meta tag

tools/integration-test-baseline.php
Until now they were not copied
=> [BUGFIX] Integration Test baseline: Copy files from subdirectories as well

tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/sitemap/expected/Sitemap.html, tests/Integration/tests-full/sitemap/expected/index.html, tests/Integration/tests-full/two-toctrees/expected/index.html, tests/Integration/tests/admonitions/expected/index.html
I merged a PR without rebasing first and did not note these tests were not up to date
=> [BUGFIX] Fix integration tests

packages/typo3-docs-theme/assets/sass/_component_bignums.scss, packages/typo3-docs-theme/assets/sass/_component_horizbuttons.scss, packages/typo3-docs-theme/resources/public/css/theme.css
=> [Bugfix] Fix bignums and horizontal buttons

packages/typo3-docs-theme/README.rst
This should trigger both initializing the subtree split trees as well as publish the assets on the CDN once tagged.
=> [TASK] Updates documentation on typo3-docs-theme

composer.lock, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/resources/languages/typoscript.json, tests/Integration/tests/code-block/with-language-aliases/expected/index.html
=> [FEATURE] Add syntax highlighting for TypoScript

packages/typo3-docs-theme/resources/languages/typoscript.json
- Remove highlighting of functions
- Remove highlighting of keys in function references
- Add highlighting of EXT: and FILE:EXT: paths
=> [TASK] Revise TypoScript code highlighting

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/resources/languages/rst.json, tests/Integration/tests/code-block/with-language-rst/expected/index.html, tests/Integration/tests/code-block/with-language-rst/input/index.rst
=> [FEATURE] Introduce basic syntax highlighting for rst

composer.lock
All our tests stay green with the latest lexer improvements. Let us see if they improve rendering time
=> [TASK] Composer update

packages/typo3-docs-theme/resources/template/structure/layout.html.twig, packages/typo3-docs-theme/src/Twig/TwigExtension.php, packages/typo3-guides-extension/resources/config/typo3-guides.php, packages/typo3-guides-extension/src/Renderer/UrlGenerator/RenderOutputUrlGenerator.php, packages/typo3-guides-extension/src/Renderer/UrlGenerator/SingleHtmlUrlGenerator.php, tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/link-wizard/expected/index.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/sitemap/expected/Sitemap.html, tests/Integration/tests-full/sitemap/expected/index.html, tests/Integration/tests-full/two-toctrees/expected/index.html, tests/Integration/tests/php-domain/expected/index.html, tests/Integration/tests/sidebar/expected/index.html, tests/Integration/tests/singlepage-by-toctree/expected/singlehtml/Index.html
depends on https://github.com/TYPO3-Documentation/render-guides/pull/242
=> [BUGFIX] Link project title to the current root document 

.github/workflows/pr-auto-approve.yaml, .github/workflows/pr-auto-merge.yaml
Only pull request where the tests are passing can be approved and merged due to the setting in the repo.
=> [CI] Approve and merge pull requests by dependabot automatically

composer.lock, packages/typo3-docs-theme/resources/template/body/menu/sitemap-level.html.twig, packages/typo3-docs-theme/resources/template/structure/navigation/menu-level.html.twig, packages/typo3-guides-extension/src/Renderer/NodeRenderer/SinglePageDocumentRenderer.php
a fix to the menu handling changed the level count in the menues. Adjusting our templates to keep the previous behaviour
NodeRenderers had a breaking change
=> [TASK] Composer update, including bugfixes due to phpdocumentor/guides update

packages/typo3-docs-theme/package-lock.json, packages/typo3-docs-theme/package.json
This change makes it clear what is needed on the live server. Additionally, an `npm update` has been run.
=> [TASK] Separate between live and development dependencies

packages/typo3-docs-theme/resources/template/structure/layout.html.twig, tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/link-wizard/expected/index.html, tests/Integration/tests-full/menu-subpages-max-1/expected/index.html, tests/Integration/tests-full/menu-subpages/expected/index.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/sitemap/expected/Sitemap.html, tests/Integration/tests-full/sitemap/expected/index.html, tests/Integration/tests-full/two-toctrees/expected/index.html
The object is not referenced anymore.
=> [TASK] Remove global object "DOCUMENTATION_OPTIONS"

composer.lock
The guides update enables external links in menues and overriding of interlink behaviours, both needed to resolve issues.
=> [TASK] Composer update includung phpdocumentor/guides

packages/typo3-docs-theme/package-lock.json, packages/typo3-docs-theme/package.json
The package is not used and therefore removed.
=> [TASK] Remove http-server dependency

Documentation/Developer/InterlinkInventories.rst, Documentation/guides.xml, guides.xml, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/DependencyInjection/Typo3DocsThemeExtension.php, packages/typo3-docs-theme/src/Inventory/DefaultInventories.php, packages/typo3-docs-theme/src/Inventory/Typo3InventoryRepository.php, packages/typo3-docs-theme/src/Inventory/Typo3VersionMapping.php, packages/typo3-docs-theme/src/Parser/ExtendedInterlinkParser.php, packages/typo3-docs-theme/tests/unit/Inventory/Typo3InventoryRepositoryTest.php
=> [FEATURE] Automatic Interlinks for extensions

phpstan-baseline.neon, phpstan.neon
Write existing reportings into baseline. They can be dealt with once the code is touched for the next time.
=> [TASK] Include cli scripts in phpstan

composer.json, composer.lock, packages/typo3-docs-theme/composer.json, packages/typo3-docs-theme/src/Inventory/Typo3InventoryRepository.php, packages/typo3-guides-cli/composer.json, packages/typo3-guides-cli/src/Migration/SettingsMigrator.php, packages/typo3-guides-cli/tests/unit/Migration/SettingsMigratorTest.php, packages/typo3-version-handling/composer.json, packages/typo3-version-handling/src/DefaultInventories.php, packages/typo3-version-handling/src/Typo3VersionMapping.php
and determine preferred TYPO3 version
=> [FEATURE] In Migration drop predefined inventories

composer.lock, tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/input/index.rst
The behaviour of guides changed regarding menus. Therefore now toctrees without titlesonly  with maxdeph display section. Added :titlesonly: to the test to keep the behaviour as before.
=> [TASK] Composer update, including phpdocumentor/guides

composer.lock, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/Directives/GroupTabDirective.php, packages/typo3-docs-theme/src/Inventory/Typo3InventoryRepository.php, packages/typo3-docs-theme/src/Renderer/DecoratingPlantumlRenderer.php, packages/typo3-docs-theme/tests/unit/Inventory/Typo3InventoryRepositoryTest.php
There have been a couple of changed and moved interface that are breaking changes in the guides.
=> [TASK] Composer update, breaking changes in the guides

Documentation/Index.rst
I added it accidently, it was only for testing
=> [TASK] Remove UML example from docs

.github/workflows/main.yaml
=> [TASK] Add "test-docs" to GitHub action

Documentation/Developer/InterlinkInventories.rst
I made an issue in the guides that this should issue a warning: https://github.com/phpDocumentor/guides/issues/821
=> [BUGFIX] Fix empty code-block

Makefile
=> [TASK] Add asset handling to makefile

composer.json, composer.lock, packages/typo3-docs-theme/composer.json, packages/typo3-docs-theme/resources/template/structure/navigation/menu-level.html.twig, packages/typo3-guides-extension/composer.json
Menu level count got fixed in the guides, so the quickfix from our template can be removed.
=> [TASK] Use tags instead of dev-main for packages where possible

composer.lock
This enables us to load the variables in twig to display project-contact etc
=> [TASK] Update phpdocumentor/guides

packages/typo3-docs-theme/resources/template/structure/layout.html.twig, tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/link-wizard/expected/index.html, tests/Integration/tests-full/menu-subpages-max-1/expected/index.html, tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html, tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html, tests/Integration/tests-full/menu-subpages/expected/index.html, tests/Integration/tests-full/meta-data/expected/index.html, tests/Integration/tests-full/next-prev-by-toctree/expected/four.html, tests/Integration/tests-full/next-prev-by-toctree/expected/i.html, tests/Integration/tests-full/next-prev-by-toctree/expected/index.html, tests/Integration/tests-full/next-prev-by-toctree/expected/one.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html, tests/Integration/tests-full/next-prev-by-toctree/expected/two.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/two-toctrees/expected/index.html
It got accidently deleted during rebasing
=> [BUGFIX] Restore Footer

packages/typo3-version-handling/README.rst
This should also trigger the initial split deployment
=> [TASK] Add a README for the version handling package

bin/guides
I honestly don't know why this didn't raise issues yet, but it does not in my WYSIWYG testing environment. :-)
=> [BUGFIX] Fixes bad shebang entrypoint

composer.json, composer.lock
The minimum PHP version for this project is PHP 8.1, so no need to load those polyfills.
=> [TASK] Remove polyfills for PHP 8.0/8.1

tests/Integration/tests/roles/role-file/expected/index.html, tests/Integration/tests/roles/role-file/input/index.rst
references https://github.com/TYPO3-Documentation/render-guides/issues/335
=> [TASK] Add test for file text role.

packages/typo3-docs-theme/resources/template/structure/layoutParts/pageHeader.html.twig, tests/Integration/tests-full/edit-on-github/expected/index.html, tests/Integration/tests-full/edit-on-github/expected/page1.html, tests/Integration/tests-full/edit-on-github/expected/subpages/index.html, tests/Integration/tests-full/index/expected/index.html, tests/Integration/tests-full/link-wizard/expected/index.html, tests/Integration/tests-full/menu-subpages-max-1/expected/index.html, tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html, tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html, tests/Integration/tests-full/menu-subpages/expected/index.html, tests/Integration/tests-full/meta-data/expected/index.html, tests/Integration/tests-full/next-prev-by-toctree/expected/four.html, tests/Integration/tests-full/next-prev-by-toctree/expected/i.html, tests/Integration/tests-full/next-prev-by-toctree/expected/index.html, tests/Integration/tests-full/next-prev-by-toctree/expected/one.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html, tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html, tests/Integration/tests-full/next-prev-by-toctree/expected/two.html, tests/Integration/tests-full/next-prev/expected/index.html, tests/Integration/tests-full/next-prev/expected/page.html, tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html, tests/Integration/tests-full/page-with-subpages/expected/index.html, tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html, tests/Integration/tests-full/page-with-subpages/expected/sub/index.html, tests/Integration/tests-full/two-toctrees/expected/index.html
resolves https://github.com/TYPO3-Documentation/render-guides/issues/344
=> [BUGFIX] Reintroduce Global Search

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/EventListeners/IgnoreLocalizationsFolder.php, packages/typo3-docs-theme/src/EventListeners/IgnoreLocalizationsFolders.php
resolves https://github.com/TYPO3-Documentation/render-guides/issues/348
=> [BUGFIX] Ignore localization folders

composer.lock, tests/Integration/tests/index/expected/objects.inv.json
=> [TASK] Update Guides

tests/Integration/tests/typo3_core_preferred/expected/index.html, tests/Integration/tests/typo3_core_preferred/input/guides.xml, tests/Integration/tests/typo3_core_preferred/input/index.rst, tests/Integration/tests/typo3_core_preferred/input/skip
references https://github.com/TYPO3-Documentation/render-guides/issues/364
=> [TASK] Add skipped test for setting typo3-core-preferred

composer.lock, tests/Integration/tests/markdown/expected/README.html
This resolves error when rst filename only contains numbers
=> [TASK] Bump guides to 0.3.7

packages/typo3-docs-theme/resources/template/body/directive/guides/inventories.html.twig, packages/typo3-docs-theme/src/Twig/TwigExtension.php, tests/Integration/tests/guides-inventories/expected/index.html, tests/Integration/tests/guides-inventories/input/index.rst
They can be documented by using directive ..  guides:inventories::
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/373
=> [FEATURE] List available standard inventories

tests/Integration/tests-full/external-menu/expected/index.html, tests/Integration/tests-full/external-menu/input/guides.xml, tests/Integration/tests-full/external-menu/input/index.rst, tests/Integration/tests-full/external-menu/input/skip, tests/Integration/tests-full/external-menu/input/subpage/index.rst
references: https://github.com/TYPO3-Documentation/render-guides/issues/375
=> [TASK] Skipped test for external links on subpages

composer.json, composer.lock, packages/typo3-docs-theme/composer.json, packages/typo3-guides-extension/composer.json
and t3docs/guides-php-domain: 1.0
Additonally bump versions where needed
=> [TASK] Use phpdocumentor/guides 1.0

packages/typo3-docs-theme/assets/sass/_variables.scss, packages/typo3-docs-theme/assets/sass/components/directives/_admonition.scss, packages/typo3-docs-theme/resources/public/css/theme.css, packages/typo3-docs-theme/resources/template/body/admonition.html.twig, tests/Integration/tests/admonitions/expected/index.html, tests/Integration/tests/admonitions/input/index.rst
Additionally, danger and error have been missing in the template.
Related: #383
=> [TASK] Restyle admonitions

packages/typo3-docs-theme/src/DependencyInjection/Typo3DocsThemeExtension.php, packages/typo3-docs-theme/src/Twig/TwigExtension.php, packages/typo3-guides-cli/src/Command/ConfigureCommand.php, packages/typo3-guides-cli/src/Migration/HtmlThemeOptions.php, packages/typo3-guides-cli/tests/unit/Migration/SettingsMigratorTest.php, tests/Integration/tests-full/edit-on-github-directory/expected/Index.html, tests/Integration/tests-full/edit-on-github-directory/input/Index.rst, tests/Integration/tests-full/edit-on-github-directory/input/guides.xml
=> [BUGFIX] Edit on GitHub Button with adjusted path

packages/typo3-docs-theme/assets/sass/_text.scss, packages/typo3-docs-theme/resources/public/css/theme.css
Hello,
This one is focused on the **links underline**.
Rachel
=> [Task] Styles link underline

packages/typo3-docs-theme/assets/sass/components/_pagination.scss, packages/typo3-docs-theme/assets/sass/theme.scss, packages/typo3-docs-theme/resources/public/css/theme.css
Hello,
This one is focused on **improving pagination**.
Rachel
=> [Task] Styles pagination

packages/typo3-docs-theme/assets/sass/layout/navigation/_main_navigation.scss, packages/typo3-docs-theme/resources/public/css/theme.css
Hello,
This one is focused on improving the **main navigation**.
Rachel
=> [Task] Styles main navigation

packages/typo3-docs-theme/assets/sass/_variables.scss, packages/typo3-docs-theme/assets/sass/components/_code.scss, packages/typo3-docs-theme/resources/public/css/theme.css
Hello,
This one is focused on the **inline-code**. 
Rachel
=> [Task] Styles inline code

Documentation-rendertest/ImagesAndFigures/Index.rst
directives must end on an empty line
=> [TASK] Correct image directive syntax

.github/workflows/main.yaml, Makefile
Should always render without warning.
=> [TASK] Add automatic testing for rendertest

Documentation-rendertest/ListsAsButtons/Index.rst
* Actually the rst-class vs class is not a thing in the guides as we use php:class for a class
* This is not a manual, just a render test
* We will change the colors
=> [TASK] Overhaul list as buttons page

Documentation-rendertest/PhpDomain/Index.rst, composer.lock
=> [TASK] Update t3docs/guides-php-domain

packages/typo3-docs-theme/resources/template/body/directive/php/partials/linkToSnippet.html.twig, packages/typo3-docs-theme/src/Twig/TwigExtension.php, tests/Integration/tests/php-domain/expected/index.html
=> [TASK] Adjust link wizard for PHP domain components

tests/Integration/tests-full/breadcrumb/expected/index.html, tests/Integration/tests-full/breadcrumb/expected/page.html, tests/Integration/tests-full/breadcrumb/expected/yetAnotherPage.html, tests/Integration/tests-full/breadcrumb/input/index.rst, tests/Integration/tests-full/breadcrumb/input/page.rst, tests/Integration/tests-full/breadcrumb/input/yetAnotherPage.rst
resolves https://github.com/TYPO3-Documentation/render-guides/issues/472
=> [TASK] Add test for special signs in page titles

packages/typo3-docs-theme/assets/sass/components/_code.scss, packages/typo3-docs-theme/resources/public/css/theme.css
resolves https://github.com/TYPO3-Documentation/render-guides/issues/509
=> [BUGFIX] Remove massive gap around code-blocks

composer.lock, packages/typo3-guides-cli/tests/unit/Migration/SettingsMigratorTest.php, tests/Integration/tests-full/index/expected/objects.inv.json, tests/Integration/tests-full/meta-data/expected/objects.inv.json, tests/Integration/tests/configuration/expected/objects.inv.json, tests/Integration/tests/index/expected/objects.inv.json
- Solve PHP unit deprecations
- Adjust tests for objects.inv.json after changed tests
=> [TASK] Update guides, phpunit and others

Documentation-rendertest/Accordion/Index.rst
There are some style issues to be resolved in another PR See https://github.com/TYPO3-Documentation/render-guides/issues/512
=> [TASK] Add render test for Bootstrap accordion

Documentation-rendertest/Cards/Index.rst
There are some style issues to be resolved in another PR, see https://github.com/TYPO3-Documentation/render-guides/issues/514
=> [TASK] Add render test for Bootstrap cards

packages/typo3-docs-theme/assets/sass/components/_card.scss, packages/typo3-docs-theme/resources/public/css/theme.css
Hello,
This PR improve styles of bootstrap cards as expected in #514
=> [TASK] Improve styles in bootstrap cards

Documentation-rendertest/Lists/Index.rst, packages/typo3-docs-theme/assets/sass/_text.scss, packages/typo3-docs-theme/assets/sass/components/directives/_admonition.scss, packages/typo3-docs-theme/assets/sass/theme.scss, packages/typo3-docs-theme/resources/public/css/theme.css
* unify handling of li, p, etc Use css variables instead of special color definitions
* Raise contrast for body text
Resolves #493, #492
=> [TASK] Include bootstrap reboot

composer.lock, packages/typo3-docs-theme/resources/template/body/directive/php/partials/linkToSnippet.html.twig, tests/Integration/tests/php-domain/expected/index.html, tests/Integration/tests/php-domain/input/index.rst
noindex feature is available now
=> [TASK] Update guides-phpdomain

packages/typo3-docs-theme/resources/template/body/directive/confval.html.twig, tests/Integration/tests/confval/confval-basic/expected/index.html, tests/Integration/tests/confval/confval-duplicate-with-name/expected/anotherDomain.html, tests/Integration/tests/confval/confval-duplicate-with-name/expected/index.html, tests/Integration/tests/confval/confval-duplicate/expected/anotherDomain.html, tests/Integration/tests/confval/confval-duplicate/expected/index.html, tests/Integration/tests/confval/confval-menu-tree-multiple/expected/index.html, tests/Integration/tests/confval/confval-menu-tree/expected/index.html, tests/Integration/tests/confval/confval-noindex/expected/anotherDomain.html
resolves https://github.com/TYPO3-Documentation/render-guides/issues/540
=> [BUGFIX] Use correct anchor in confval template

Documentation-rendertest/Typesetting/Index.rst, packages/typo3-docs-theme/resources/template/structure/navigation/menu-level.html.twig, packages/typo3-docs-theme/src/Twig/TwigExtension.php
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/545
=> [BUGFIX] Use plaintext for titles in menues

composer.lock, tests/Integration/tests/php-domain/expected/index.html
resolves https://github.com/TYPO3-Documentation/render-guides/issues/551
=> [BUGFIX] Update phpdomain extension

Documentation-rendertest/Confval/Index.rst, composer.lock, tests/Integration/tests/confval/confval-basic/expected/index.html, tests/Integration/tests/confval/confval-duplicate-with-name/expected/anotherDomain.html, tests/Integration/tests/confval/confval-duplicate-with-name/expected/index.html, tests/Integration/tests/confval/confval-duplicate/expected/anotherDomain.html, tests/Integration/tests/confval/confval-duplicate/expected/index.html, tests/Integration/tests/confval/confval-menu-tree/expected/index.html, tests/Integration/tests/confval/confval-noindex/expected/anotherDomain.html, tests/Integration/tests/confval/confval-noindex/expected/index.html
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/554
=> [BUGFIX] Allow required: false in confvals

Documentation-rendertest/Confval/ConfvalTrees.rst, packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig, packages/typo3-docs-theme/resources/template/body/directive/confval.html.twig, packages/typo3-docs-theme/src/Directives/ConfvalMenuDirective.php, packages/typo3-docs-theme/src/Nodes/ConfvalMenuNode.php, tests/Integration/tests/confval/confval-basic/expected/index.html, tests/Integration/tests/confval/confval-duplicate-with-name/expected/anotherDomain.html, tests/Integration/tests/confval/confval-duplicate-with-name/expected/index.html, tests/Integration/tests/confval/confval-duplicate/expected/anotherDomain.html, tests/Integration/tests/confval/confval-duplicate/expected/index.html, tests/Integration/tests/confval/confval-menu-tree-multiple/expected/index.html, tests/Integration/tests/confval/confval-menu-tree-multiple/input/index.rst, tests/Integration/tests/confval/confval-menu-tree/expected/index.html, tests/Integration/tests/confval/confval-menu-tree/input/index.rst, tests/Integration/tests/confval/confval-noindex/expected/anotherDomain.html, tests/Integration/tests/confval/confval-noindex/expected/index.html
=> [FEATURE] Add back to list / back to top buttons to confvals

packages/typo3-docs-theme/assets/sass/_text.scss, packages/typo3-docs-theme/resources/public/css/theme.css, packages/typo3-docs-theme/resources/template/inline/link.html.twig, tests/Integration/tests/interlink/interlink-warn/expected/index.html, tests/Integration/tests/interlink/interlink-warn/expected/logs/warning.log, tests/Integration/tests/interlink/interlink-warn/input/guides.xml, tests/Integration/tests/interlink/interlink-warn/input/index.rst
=> [TASK] Display placeholders for unresolved references

Documentation-rendertest/Localization.ru_RU/UserManagement/GroupPermissions/Index.rst
This setting was removed with TYPO3 13
=> [TASK] Remove link

packages/typo3-docs-theme/src/Directives/LiteralincludeDirective.php, tests/Integration/tests/code-block/literalinclude/expected/Index.html, tests/Integration/tests/code-block/literalinclude/input/Index.rst, tests/Integration/tests/code-block/literalinclude/input/_code/_Example.php, tests/Integration/tests/code-block/literalinclude/input/_code/_Services.yaml, tests/Integration/tests/code-block/literalinclude/input/_code/_Template.html, tests/Integration/tests/code-block/literalinclude/input/_code/_composer.json, tests/Integration/tests/code-block/literalinclude/input/_code/_setup.typoscript, tests/Integration/tests/code-block/literalinclude/input/_code/_some.diff, tests/Integration/tests/code-block/literalinclude/input/_code/_some.yml, tests/Integration/tests/code-block/literalinclude/input/_code/_test.txt, tests/Integration/tests/code-block/literalinclude/input/guides.xml, tests/Integration/tests/edit-on-github/edit-on-github-literalinclude/input/Index.rst
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/600
=> [FEATURE] Autodetect code language of literalincludes

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/resources/template/inline/textroles/t3src.html.twig, packages/typo3-docs-theme/src/Inventory/Typo3InventoryRepository.php, packages/typo3-docs-theme/src/Inventory/Typo3VersionService.php, packages/typo3-docs-theme/src/Twig/TwigExtension.php, packages/typo3-docs-theme/tests/unit/Inventory/Typo3InventoryRepositoryTest.php, tests/Integration/tests/roles/role-t3src-core-prefered/expected/index.html, tests/Integration/tests/roles/role-t3src-core-prefered/input/guides.xml, tests/Integration/tests/roles/role-t3src-core-prefered/input/index.rst
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/603
=> [BUGFIX] Respect typo3-core-preferred for t3src roles

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/resources/template/body/directive/viewhelper.html.twig, packages/typo3-docs-theme/resources/template/body/directive/viewhelper/viewhelper-argument.html.twig, packages/typo3-docs-theme/resources/template/body/directive/viewhelper/viewhelper-source.html.twig, packages/typo3-docs-theme/src/Directives/ViewHelperDirective.php, packages/typo3-docs-theme/src/Nodes/ViewHelperArgumentNode.php, packages/typo3-docs-theme/src/Nodes/ViewHelperNode.php, phpstan-baseline.neon, tests/Integration/tests-full/changelog/expected/Changelog/12.0/Index.html, tests/Integration/tests/roles/role-composer/expected/index.html, tests/Integration/tests/viewhelper/expected/index.html, tests/Integration/tests/viewhelper/input/index.rst, tests/Integration/tests/viewhelper/input/resources/global_viewhelpers_demo.json
This directive displays the ViewHelper from a json input
=> [FEATURE] Introduce viewhelper directive

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/Directives/ViewHelperDirective.php, packages/typo3-docs-theme/src/TextRoles/CustomLinkTextRole.php, packages/typo3-docs-theme/src/TextRoles/ViewhelperArgumentTextRole.php, packages/typo3-docs-theme/src/TextRoles/ViewhelperTextRole.php, packages/typo3-docs-theme/src/Twig/TwigExtension.php, tests/Integration/tests/viewhelper/expected/index.html, tests/Integration/tests/viewhelper/expected/objects.inv.json, tests/Integration/tests/viewhelper/input/index.rst
resolves https://github.com/TYPO3-Documentation/render-guides/issues/630
=> [TASK] Make ViewhelperArguments Linkable

packages/typo3-api/template/components/deprecation.html.twig
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/648
=> [BUGFIX] Fix deprecation notice in api.typo3.org

packages/typo3-api/redirect.php, packages/typo3-api/template/new_urls.json.twig
References https://github.com/TYPO3-Documentation/render-guides/issues/654
=> [TASK] Create redirecs for api.typo3.org

packages/typo3-api/redirect.php, packages/typo3-docs-theme/resources/template/body/directive/viewhelper.html.twig, tests/Integration/tests/viewhelper/expected/index.html
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/657
=> [TASK] Show information that VH allows arbitrary arguments

packages/typo3-docs-theme/resources/template/body/directive/viewhelper.html.twig, tests/Integration/tests/viewhelper/expected/index.html
resolves https://github.com/TYPO3-Documentation/t3docs-typo3-docs-theme/pull/1
=> [BUGFIX] ViewHelper mark inline code correctly

Documentation/Developer/InterlinkInventories.rst, packages/typo3-version-handling/src/DefaultInventories.php, tests/Integration/tests/guides-inventories/expected/index.html
for links to documentation start page
=> [FEATURE] Add t3docs interlink key

packages/typo3-docs-theme/src/TextRoles/PhpTextRole.php, tests/Integration/tests/code/code-php/expected/index.html
resolves https://github.com/TYPO3-Documentation/render-guides/issues/688
=> [TASK] Change label of unknown classes

Documentation-rendertest/Confval/ConfvalTrees.rst, packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig, packages/typo3-docs-theme/src/Directives/ConfvalMenuDirective.php, packages/typo3-docs-theme/src/Directives/SiteSetSettingsDirective.php, packages/typo3-docs-theme/src/Nodes/ConfvalMenuNode.php, tests/Integration/tests/confval/confval-menu-tree-anchor/expected/index.html, tests/Integration/tests/confval/confval-menu-tree-multiple/expected/index.html, tests/Integration/tests/confval/confval-menu-tree/expected/index.html, tests/Integration/tests/site-set-ext-syntax/expected/index.html, tests/Integration/tests/site-set-failure/expected/index.html, tests/Integration/tests/site-set/expected/index.html
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/707
=> [BUGIFIX] In confval-menu, shorten long default values

Documentation-rendertest/Confval/ConfvalTrees.rst, Documentation-rendertest/PhpDomain/Index.rst, composer.lock, packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig, packages/typo3-docs-theme/resources/template/body/directive/confval.html.twig, packages/typo3-docs-theme/resources/template/body/directive/php/memberName.html.twig, packages/typo3-docs-theme/resources/template/body/directive/php/partials/codeStyle.html.twig, packages/typo3-docs-theme/resources/template/inline/textroles/code.html.twig, packages/typo3-docs-theme/resources/template/inline/textroles/file.html.twig, packages/typo3-docs-theme/resources/template/inline/textroles/path.html.twig, packages/typo3-docs-theme/resources/template/inline/textroles/unknown.html.twig, packages/typo3-docs-theme/src/Parser/ExtendedInterlinkParser.php, packages/typo3-docs-theme/src/TextRoles/CustomLinkTextRole.php, packages/typo3-docs-theme/src/Twig/TwigExtension.php, tests/Integration/tests-full/changelog/expected/Changelog/12.0/Breaking-87616-RemovedHookForAlteringPageLinks.html, tests/Integration/tests/code-inline/expected/index.html, tests/Integration/tests/code/code-php/expected/index.html, tests/Integration/tests/confval/confval-menu-tree-anchor/expected/index.html, tests/Integration/tests/confval/confval-menu-tree-multiple/expected/index.html, tests/Integration/tests/confval/confval-menu-tree/expected/index.html, tests/Integration/tests/directory-tree/expected/index.html, tests/Integration/tests/file/expected/index.html, tests/Integration/tests/php-domain/expected/index.html, tests/Integration/tests/roles/role-file/expected/index.html, tests/Integration/tests/site-set-ext-syntax/expected/index.html, tests/Integration/tests/site-set/expected/index.html, tests/Integration/tests/viewhelper/expected/index.html
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/719
=> [TASK] Use "Line Break Opportunity" tags in confvals

Documentation-rendertest/Admonitions-and-buttons/Index.rst, packages/typo3-docs-theme/resources/template/body/admonition.html.twig
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/725
=> [BUGFIX] Prevent duplicate titles in admonitions

packages/typo3-docs-theme/src/Directives/SiteSetSettingsDirective.php, tests/Integration/tests/site-set-labels/expected/index.html, tests/Integration/tests/site-set-labels/input/_includes/Configuration/Sets/Felogin/config.yaml, tests/Integration/tests/site-set-labels/input/_includes/Configuration/Sets/Felogin/settings.definitions.yaml, tests/Integration/tests/site-set-labels/input/_includes/Resources/Private/Language/locallang_set.xlf, tests/Integration/tests/site-set-labels/input/index.rst
Required prerequisite for:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/85869
https://forge.typo3.org/issues/104831
=> [TASK] Allow settings labels to be provided in xlf files

Documentation-rendertest/Confval/ConfvalTrees.rst, packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/747
=> [BUGFIX] Display "required" correctly in confval tables

packages/typo3-docs-theme/src/Twig/TwigExtension.php, packages/typo3-version-handling/src/Typo3VersionMapping.php, tests/Integration/tests-full/changelog/expected/Changelog/12.0/Breaking-87616-RemovedHookForAlteringPageLinks.html, tests/Integration/tests-full/changelog/expected/Changelog/12.0/Index.html, tests/Integration/tests-full/changelog/expected/Index.html, tests/Integration/tests-full/changelog/expected/Sitemap.html, tests/Integration/tests-full/report-issue/report-issue-forge/expected/index.html
Resolves: https://github.com/TYPO3-Documentation/render-guides/issues/741
=> [BUGFIX] Fix version parameter in forge issue links

packages/typo3-docs-theme/resources/template/structure/navigation/navigationHeader.html.twig, packages/typo3-docs-theme/src/DependencyInjection/Typo3DocsThemeExtension.php, tests/Integration/tests-full/disabled-version-switch/expected/index.html, tests/Integration/tests-full/disabled-version-switch/input/guides.xml, tests/Integration/tests-full/disabled-version-switch/input/index.rst
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/758
=> [TASK] Disable Language Switch if needed

.php-cs-fixer.dist.php, phpstan.neon
Include missing package in phpstan
=> [TASK] Only run php-cs-fixer on local packages

Documentation-rendertest/SiteSettings/SiteSettingsWithLabels/Index.rst, Documentation-rendertest/SiteSettings/SiteSettingsWithLabels/_siteSetSettings.rst.txt, Documentation-rendertest/SiteSettings/SiteSettingsWithLabels/labels.xlf, Documentation-rendertest/SiteSettings/SiteSettingsWithLabels/settings.definitions.yaml, Documentation-rendertest/SiteSettings/settings.definitions.yaml, packages/typo3-docs-theme/src/Directives/SiteSetSettingsDirective.php
=> [TASK] Display site setting categories

composer.json, composer.lock, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/resources/template/structure/layoutParts/editOnGithubButtons.html.twig, packages/typo3-docs-theme/resources/template/structure/navigation/meta-menu.html.twig, packages/typo3-docs-theme/src/EventListeners/OriginalFileNameSetter.php, packages/typo3-docs-theme/src/Twig/TwigExtension.php, packages/typo3-guides-extension/composer.json, tests/Integration/tests-full/main-menu-json/expected/index.html, tests/Integration/tests-full/main-menu-json/expected/mainmenu.json, tests/Integration/tests/markdown/expected/README.html, tests/Integration/tests/roles/role-composer/expected/index.html
This will make markdown rendering work with less errors.
=> [FEAT] use current filename to get the original file name

Documentation-rendertest/Typesetting/Index.rst, packages/typo3-docs-theme/assets/sass/_variables.scss, packages/typo3-docs-theme/resources/public/css/theme.css
=> Adjust line-height for headings + add example for a heading with code and a linebreak

packages/typo3-docs-theme/assets/sass/components/directives/_confval.scss, packages/typo3-docs-theme/assets/sass/components/directives/_phpdomain.scss, packages/typo3-docs-theme/assets/sass/components/directives/_propertyCard.scss, packages/typo3-docs-theme/assets/sass/theme.scss, packages/typo3-docs-theme/resources/public/css/theme.css
Introduce property-card as central element for such cases + Style PHP-Classes like confvals
resolves #560
=> Style PHP-Classes + Add property-card als central styling for property-cards

.github/workflows/docker.yaml
=> [TASK] update docker build workflow

Documentation-markdowntest/Index.md, Documentation-markdowntest/guides.xml, Makefile, composer.json, composer.lock, guides.xml
You can try out conversion with
```make mdtest```
=> [FEATURE] Make convert markdown to reST available

composer.json, composer.lock, packages/typo3-docs-theme/composer.json
No functional changes, just bumped to a stable version.
=> chore: update twig-codehighlight to 1.0.0

packages/typo3-docs-theme/src/TextRoles/FileTextRole.php, tests/Integration/tests/typo3-file/expected/index.html, tests/Integration/tests/typo3-file/input/index.rst
It causes bugs and needs special handling
=> [BUGFIX] Remove Interlink handling for files for now

Documentation-rendertest/Inline-code-and-textroles/Index.rst, packages/typo3-docs-theme/resources/config/typo3-docs-theme.php, packages/typo3-docs-theme/src/TextRoles/CssTextRole.php, packages/typo3-docs-theme/src/TextRoles/ScssTextRole.php, tests/Integration/tests/code-inline/expected/index.html
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/555
=> [FEATURE] Add text roles for css and scss

composer.json, composer.lock, packages/typo3-guides-extension/composer.json
=> [TASK] bump guides

composer.json, composer.lock
=> [BUGFIX] Downgrade symplify/monorepo-builder to ^11.2
