TYPO3-Documentation/render-guides

.dockerignore
.github/workflows/docker.yaml
Dockerfile
composer.json
composer.lock

By moving the build step into a separate stage we have a smaller docker images which speeds up the downloads of the docker image. Therefor I also switched to the alpine image to get as small as possible.
I added a workflow that will build 3 docker images for different cpu architectures. Amd64, what most servers and laptops are using nowdays. Arm/7 for the odd people using a raspberry pi to run their build pipeline. And arm64 for Mac users. The new MacBooks will take advantage of this last version. As the os doesn't have to virtualize the amd64. So docker can be executed natively on the cpu. 
More changes can be added later, when we want to reduce the size even more.

[FEATURE] Improve docker build setup

---

composer.json
composer.lock
fixtures/markdown/README.md
guides.xml

Markdown rendering still has a lot of flaws that are adressed in https://github.com/phpDocumentor/guides/pull/640
Some errors are fixed there (like the warnings going to the log instead of the console and output of simple paragraphs)
For others I added skiped tests
For now the rendering can be tried out with
ddev exec vendor/bin/guides fixtures/markdown output --input-file=README.md

[FEATURE] Enable Markdown rendering

---

entrypoint.sh

The container will switch by default to a non root user. When the user flag is used, we do need this logic. We can just execute as the provided user id.

[TASK]: allow container execution with non root user

---

README.rst

Currently, running the command fails with the error:
Too many arguments, expected arguments "input".

[DOCS] Fix docker command in readme

---

Makefile
README.rst
tools/add-githooks.sh
tools/githook-templates/commit-msg
tools/githook-templates/pre-commit

This allows contributors to execute:
`make githooks` (or: `./tools/add-githooks.sh` directly)
This in turn copies the tools/githook-templates/ files to the local git directory for the project.
That in turn executes commit message line length inspection and executes `make pre-commit-test` before any commit.
TODO: At least for me sadly currently `make pre-commit-test` (macOS) does not work, complains about a missing entry point. But this is independent from what this commit does.

[FEATURE] Add helper script to inject git hooks (commit-msg+pre-commit)

---

Documentation/Developer/Building.rst
Documentation/Developer/Directory-structure.rst
Documentation/Developer/Index.rst
Documentation/Developer/Mono-repository.rst
Documentation/Developer/Theme-customization.rst
Documentation/Includes.rst.txt
Documentation/Index.rst
Documentation/Installation/Index.rst
Documentation/Introduction/Index.rst
Documentation/KnownProblems/Index.rst
Makefile
composer.lock
guides.xml

Following the default setup of other documentation projects this patch adss a first set of documentation to help future developer to maintain and improve the project.
More documentation is needed. But we should also link to the guides documentation. That needs to be written and published.

[TASK] add first documentation setup

---

action.yml
entrypoint.sh

The default location for guides.xml is Documentation, people might decide to do it different, so make it configurable.
I update the entrypoint to fix an issue when the input argument was omitted. The previous implementation did quote all arguments. But that broke the optional input argument as it would always be `""` when left empty. 
While testing this behavior I found another issue, that was giving some odd errors when a user does not specify a volume, we to now exit with an error message.

[TASK] relocate config to Documentation

---

Documentation/Developer/Building.rst

There always has to be an empty line after the two collons

[DOCS] Fix codeblock

---

Documentation/guides.xml
Makefile
guides.xml

Guides.xml at root level is used as default for all projects, our specific config is in Documentation.

[TASK] Add guides.xml in the documentation dir

---

Dockerfile
Makefile

The single page format requires a bit more memory because all html is kept in memory during rendering.

[TASK] set mem limit in docker to 1G

---

packages/php-domain/src/PhpDomain/MethodNameService.php

This fixes the phpstan error:
------ -----------------------------------------------------------------------
Line   php-domain/src/PhpDomain/MethodNameService.php
------ -----------------------------------------------------------------------
13     Add regex101.com link to that shows the regex in practise, so it will
be easier to maintain in case of bug/extension in the future
------ -----------------------------------------------------------------------
Related: #66 
Related: #68

[BUGFIX] Fix failing regex validation

---

Documentation/Developer/Building.rst
Documentation/Installation/Index.rst
Makefile
README.rst
entrypoint.sh

Docker on macOS runs as root. If the entrypoint.sh is then executed, it sees that the `/project` directory is also mounted as root.
In that case, the script fails because it seems to expect that `/project` should belong to a specific user. However, the `Dockerfile` does currently NOT fix the workspace to a user like `typo3`.
Thus, the script only works if either:
* --user is specified or
* docker is automatically run with the current user (seems to be the case in Linux+Windows)
This PR addresses to document this behaviour.

[DOCS] Document "docker run" issues with macOS, where "--user" is required

---

Documentation/Introduction/Index.rst
Documentation/guides.xml

This also introduces an interlink into our documentation as example

[DOCS] Link to "How to document" from docs

---

packages/typo3-docs-theme/resources/template/structure/layout.html.twig
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/index/expected/objects.inv.json
tests/Integration/tests-full/index/input/guides.xml
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/sitemap/expected/Sitemap.html
tests/Integration/tests-full/sitemap/expected/index.html

The metadata title missed the - sign and a whitespace, order was wrong docsearch:release and docsearch:version should contain the configured version - if any docsearch:name should contain the name of the project, not of the current document
Also output the version in DOCUMENTATION_OPTIONS

[BUGFIX] Fix the metadata

---

tests/Integration/tests/code-block/with-emphasize-lines/input/skip

This issue was resolved by https://github.com/phpDocumentor/guides/pull/690.

[TASK] Remove skip of emphasize-lines from code-block

---

.ddev/config.yaml
.ddev/nginx/index.conf

As the generated documentation folder is named "Documentation-GENERATED-temp" this is set as docroot.
Additionally, add Index.html (with capitalized I) as index file.

[TASK] Adjust docroot of ddev configuration

---

packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php

While the php-ini format only knows ; or // or ## as comments in the settings.cfg single # are used as comment. So these lead to problems

[BUGFIX] Remove comments from the settings.cfg before migration

---

packages/typo3-docs-theme/resources/template/structure/layout.html.twig
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/sitemap/expected/Sitemap.html
tests/Integration/tests-full/sitemap/expected/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

- Remove superfluous closing `/`
- Remove superfluous `type="text/css"` in stylesheet links
- Remove superfluous `type="text/javascript"` in script tags

[TASK] Cleanup layout template

---

packages/typo3-docs-theme/resources/template/structure/layout.html.twig
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/sitemap/expected/Sitemap.html
tests/Integration/tests-full/sitemap/expected/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

It is not used either in the HTML or in the JavaScripts.

[TASK] Remove embedding Modernizr

---

.ddev/config.yaml

Unfortunary nodejs 20 does not run on my current machine as I cannot upgrade my ddev. As soon as I have upgraded my hardware we can switch back to nodejs 20.

[TASK] Downgrade to nodejs 18

---

composer.json
packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
packages/typo3-guides-cli/src/Repository/Exception/FileException.php
packages/typo3-guides-cli/src/Repository/LegacySettingsRepository.php
packages/typo3-guides-cli/tests/fixtures/Settings.cfg
packages/typo3-guides-cli/tests/unit/Repository/Exception/FileExceptionTest.php
packages/typo3-guides-cli/tests/unit/Repository/LegacySettingsRepositoryTest.php

This is the first step in refactoring the "god" command class for migrating settings. The handling of reading and parsing of the Settings.cfg is moved into a separate class.
Additionally, now we can add initial unit tests.

[TASK] Move logic for parsing Settings.cfg into a separate class

---

composer.lock

The logger will be injected automatically by dependency injection.
A log entry looks now like this:
[2023-11-25T19:34:34.186907+01:00] app.WARNING: Language "kjsdfhs" is not available to highlight code [] []

[TASK] Update codehighlight extension to log non-existing languages

---

.github/workflows/phar.yaml

shivammathur/setup-php@v2 currently fails with PHP 8.3 See for example https://github.com/TYPO3-Documentation/render-guides/actions/runs/6995451358/job/19030317471?pr=144

[BUGFIX] Limit PHP to 8.1 during phar building.

---

packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
packages/typo3-guides-cli/src/Migration/Deprecated.php
packages/typo3-guides-cli/src/Migration/HtmlThemeOptions.php
packages/typo3-guides-cli/src/Migration/Project.php
packages/typo3-guides-cli/src/Migration/Sections.php

The goal is to reduce the "god" command for migrating the legacy configuration. This change moves the class constants into dedicated enums to decouple them from the command. A next step would be to move the logic for building the XML into a dedicated class.

[TASK] Move class constants into dedicated enums

---

.github/workflows/main.yaml
composer.json
composer.lock

Also check the normalization in the workflow run.
Additionally, a "monorepo-builder merge" was executed which added the two PHP extensions to the root composer.json.

[TASK] Normalize composer.json

---

packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
packages/typo3-guides-cli/src/Migration/SettingsMigrator.php
packages/typo3-guides-cli/src/Repository/LegacySettingsRepository.php
packages/typo3-guides-cli/tests/unit/Migration/SettingsMigratorTest.php

The return value of the migrate() method is still ugly, but can be addressed later in a separate change.
There are some glitches, like when a legacy setting has an empty value, a message "Some of your settings could not be converted" is displayed. Or if an id or value has whitespaces. This will also be addressed in a separate change to be as near as possible to the original code.
Additionally, the generating of the XML is now covered by unit tests.

[TASK] Move XML handling out of MigrateSettingsCommand

---

composer.lock

phpdocumentor/guides fixed a bug, interlink repositories with underscore are now allowed. This should greatly remove the number of warnings on rendering manuals and make it easier to debug the rest
- Upgrading friendsofphp/php-cs-fixer (v3.40.0 45a4530 => v3.40.0 27d2b32)
- Upgrading phpdocumentor/guides (dev-main 98adb65 => dev-main add1f47)
- Upgrading phpdocumentor/guides-restructured-text (dev-main 8f93858 => dev-main 9198c4c)
- Upgrading phpstan/phpstan (1.10.44 => 1.10.45)
- Upgrading t3docs/guides-php-domain (dev-main 598c70e => dev-main cd9c713)

[TASK] composer update

---

.php-cs-fixer.dist.php
composer.json
composer.lock
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/src/DependencyInjection/Typo3DocsThemeExtension.php
packages/typo3-guides-cli/src/Command/ConfigureCommand.php
packages/typo3-guides-cli/src/Command/LintGuidesXmlCommand.php
packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
packages/typo3-guides-cli/tests/unit/Migration/SettingsMigratorTest.php
packages/typo3-guides-extension/resources/config/typo3-guides.php
tests/Integration/IntegrationTest.php

This change removes the package "typo3/coding-standards" in favour of "friendsofphp/php-cs-fixer". There is no need to use this proxy package.
Instead, we define the needed rules directly. As we stick zu the PER-CS standard (the successor of PSR-12) we pin the rules to the PER-CS 1 ruleset. Additionally, we opt in for some already implemented PER-CS 2 rules to avoid too much style changes already available in the codebase.
With the pinning to defined rules we ensure that updates of php-cs-fixer does not "break" the currently used styles locally or in CI. Changes in the defined rules can therefore be done explicitly.

[TASK] Use php-cs-fixer directly

---

Documentation/Developer/Building.rst
Documentation/Developer/Contributing.rst
Documentation/Developer/DirectoryStructure.rst
Documentation/Developer/Index.rst
Documentation/Developer/MonoRepository.rst
Documentation/Developer/ThemeCustomization.rst
Documentation/Installation/Index.rst

This makes reading of the rst easier as it is explicitly visible, which language is used.

[DOCS] Use code blocks explicitly

---

README.rst

The --progress option is not necessary as the progress bar is shown by default.
The --config option is needed for now as a guides.xml from the folder of the Documentation is not interpreted by default

[DOCS] Update README.rst docker command

---

.github/actions/configure-guides-step/action.yaml
.github/actions/render-guides-step/action.yaml
.github/workflows/main.yaml
action.yml
entrypoint.sh
packages/typo3-guides-cli/src/Command/ConfigureCommand.php

This PR splits the current process of single-use rendering up into a two-step composite process as outlined in  https://github.com/TYPO3-Documentation/render-guides/issues/158
The first step takes care of configuring a local guides.xml (during rendering/GH-action only) with dynamic parameters. Those parameters fixate the input from the GitHub action for the target GIT branch and target deployment directory.
The second step is the usual rendering, which will then take into account the modified parameters, so that the rendered output includes also the non-committed changes, as the old sphinx jobfile did.
The commit includes a large addition to the `ConfigureCommand` that is needed to configure the required attributes. That code will need later refactoring and added unit testing. For now it …

[TASK] Splits GitHub rendering action into composite

---

packages/typo3-docs-theme/assets/sass/_component_docutils.scss
packages/typo3-docs-theme/assets/sass/components/_table.scss
packages/typo3-docs-theme/resources/public/css/theme.css

We use the table class of bootstrap instead of docutils now. Field lists are defined as definition lists so we need no special handling for tables with .field-list classes.
Also our table definition now extends table-striped instead of copying the styles

[TASK] Cleanup docutil table style definitions

---

packages/typo3-docs-theme/assets/sass/_component_sidebar.scss
packages/typo3-docs-theme/resources/public/css/theme.css

before:
after:
current design:

[TASK] Fix sidebar

---

composer.lock

This resolves issues with named references on documents and bootstrap tabs
Upgrading ergebnis/composer-normalize (2.40.0 => 2.41.1)
- Upgrading ergebnis/json-normalizer (4.3.0 => 4.4.1)
- Upgrading phpdocumentor/guides (dev-main f68aa11 => dev-main 0b1fea0)
- Upgrading phpdocumentor/guides-markdown (dev-main 6e29774 => dev-main 053c920)
- Upgrading phpdocumentor/guides-restructured-text (dev-main 472367b => dev-main aa801f4)
- Upgrading phpdocumentor/guides-theme-bootstrap (dev-main a48b2e9 => dev-main efced4c)
- Upgrading phpstan/phpstan (1.10.49 => 1.10.50)
- Upgrading t3docs/guides-php-domain (dev-main e92c96e => dev-main bed620c)

[TASK] Run composer update

---

.github/workflows/split-repositories.yaml
config.subsplit-publish.json

This adds:
* A GitHub workflow `.github/workflows/split-repositories.yaml` which is triggered on either any commit on `packages/` (subtree split packages) or whenever a new git tag is added
* A subtree configuration on `/config.subsplit-publish.json` that defines, which repositories are split-off into which subdirectories
This uses the `typo3-documentation-team` bot user to push commits (using `secrets.BOT_TOKEN` I have configured).

[TASK] Add subtree-split configuration

---

packages/typo3-docs-theme/src/Twig/TwigExtension.php

This should hopefully properly evaluate whether being called from within a github action and enable using the CDN.

[BUGFIX] Uses getenv('GITHUB_ACTIONS') instead of getenv('CI')

---

packages/typo3-docs-theme/assets/sass/_component_rst.scss
packages/typo3-docs-theme/assets/sass/_component_versionchanged.scss
packages/typo3-docs-theme/assets/sass/theme.scss
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/body/version-change.html.twig

I would like to suggest the following styles for version changed, deprecated etc directives:

[TASK] New styling for version directives

---

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php

To avoid warnings when rendering the docs until the `highlight.php` language for restructured text is available.
Related: #173

[TASK] Add alias for code language "rst" to "plaintext"

---

packages/typo3-docs-theme/assets/sass/_webfonts.scss

We don't provide the removed files in the "fonts" folder, therefore the style definitions are removed.

[BUGFIX] Remove unavailable "Source Sans 3" font files

---

packages/typo3-docs-theme/resources/languages/typoscript.json
tests/Integration/tests/code-block/with-language-typoscript/expected/index.html
tests/Integration/tests/code-block/with-language-typoscript/input/index.rst

- Remove number recognition as it has no real value
- Add missing keywords
- Enhance path recognition
- Handle constants (`{$foo.bar}`)
- Distinct between RGB color and comments (`#000` and `#000000`)
- Distinct between SQL quotes and comments ('#fieldname')
- Add tests

[TASK] Refine TypoScript highlighting

---

Documentation/Installation/Index.rst
Documentation/Migration/Index.rst
README.rst

Missed to update this documentation when merging the Docker workflows.

[DOCS] Utilize ":latest" instead of ":main" Docker container reference

---

composer.lock
packages/typo3-docs-theme/resources/template/structure/sidebar.html.twig
packages/typo3-docs-theme/src/TextRoles/IssueReferenceTextRole.php
tests/Integration/tests/images/No-Folders/expected/index.html
tests/Integration/tests/php-domain/expected/index.html

There have been breaking changes in guides and phpdomain requiring follow up changes to get the tests green again.
Each change is in its own commit so that each one can be annotated

composer update

---

Documentation/Migration/Index.rst

Most users would run the command in the project's root folder (like now for the Sphinx rendering method). This change eases running the command, as it is just copy'n'paste now.

[DOCS] Adapt path to Documentation folder on migration

---

.github/dependabot.yml

Composer and npm updates can be created automatically using dependabot. Updates are checked on a daily basis at 16:00. For each pull request created by dependabot the labels "dependencies", and "composer" (for a Composer-related update) and "npm" for a (npm-related update) are added.
Development branched are also considered for Composer-related updates for the time being.
Updates of requirements can also be done manually at any time.

[CI] Let dependabot create PRs for updating dependencies

---

packages/typo3-docs-theme/resources/template/structure/singlepage.html.twig
packages/typo3-docs-theme/src/Twig/TwigExtension.php
packages/typo3-guides-extension/src/Renderer/SinglePageRenderer.php
tests/ApplicationTestCase.php
tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
tests/Integration/tests-full/page-with-subpages/input/guides.xml
tests/Integration/tests/singlepage-by-toctree/expected/singlehtml/Index.html
tests/Integration/tests/singlepage/expected/singlehtml/Index.html

And add an integration test for single HTML.
It was until now not possible testing it.
There are still open issues with single HTMl, but I would suggest to solve them in follow-ups.
- https://github.com/TYPO3-Documentation/render-guides/issues/238
- https://github.com/TYPO3-Documentation/render-guides/issues/239
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/233

[BUGFIX] Fix the asset paths in single HTML

---

packages/typo3-guides-extension/resources/config/typo3-guides.php
packages/typo3-guides-extension/src/Renderer/UrlGenerator/RenderOutputUrlGenerator.php
packages/typo3-guides-extension/src/Renderer/UrlGenerator/SingleHtmlUrlGenerator.php
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
tests/Integration/tests-full/sitemap/expected/Sitemap.html
tests/Integration/tests-full/sitemap/expected/index.html
tests/Integration/tests/php-domain/expected/index.html
tests/Integration/tests/sidebar/expected/index.html
tests/Integration/tests/singlepage-by-toctree/expected/singlehtml/Index.html

Make links in html always relative and in singlehtml links to documents stay within the document.
Links to resources are always relative
All tests are changed as before now the default
was absolute links, which we overrode in the guides.xml. However absolute links are not usefull for our scenario anyway so I dropped support of them. This does not change the behaviour of our rendered documents
resolves https://github.com/TYPO3-Documentation/render-guides/issues/238

[BUGFIX] Override link handling

---

Documentation/Developer/Index.rst
Documentation/Developer/InterlinkInventories.rst
Documentation/guides.xml
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/src/Inventory/DefaultInventories.php
packages/typo3-docs-theme/src/Inventory/Typo3InventoryRepository.php
packages/typo3-docs-theme/src/Inventory/Typo3VersionMapping.php
packages/typo3-docs-theme/src/Settings/Typo3DocsThemeSettings.php
packages/typo3-docs-theme/tests/unit/Inventory/Typo3InventoryRepositoryTest.php
packages/typo3-guides-extension/resources/config/typo3-guides.php

I will deal with third party extensions in a follow up
Now all common core manuals are predefined. You can call to them without prefix which gives you the preferred version
t3coreapi
If no preferred version is set, stable is used.
You can call also with different prefixes
t3coreapi_dev
t3coreapi_stable
t3coreapi_oldstable
t3coreapi_latest
What versions these go to is defined in Typo3DocsThemeSettings
The prefixes work for any manual that supports versions.
As Interlink inventories are only querried the first time they are used unused inventories, even in a large number should not influence performance notably.
If a version did not exist yet, for example sys_note in version oldstable the normal warning like for a miss configured manual inventory is displayed and the link not expressed.

[FEATURE] Automatic interlinks to Core manuals

---

packages/typo3-docs-theme/assets/sass/_component_page.scss
packages/typo3-docs-theme/resources/public/css/theme.css

No idea when this got broken, but right now it looks like this:
After the change the margins and paddings are calculated like before:

[BUGFIX] Fix mobile menu header

---

packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
packages/typo3-guides-cli/src/Migration/Exception/ProcessingException.php
packages/typo3-guides-cli/src/Migration/Processor.php
packages/typo3-guides-cli/tests/unit/Command/MigrateSettingsCommandTest.php
packages/typo3-guides-cli/tests/unit/Migration/ProcessingExceptionTest.php
packages/typo3-guides-cli/tests/unit/Migration/ProcessorTest.php

The command can be seen as a controller, it should not hold logic outside controlling. Therefore, the processing is moved into a dedicated class.
Now we can also test the command class easily.

[TASK] Move processing logic out of MigrateSettingsCommand

---

packages/typo3-guides-cli/src/Command/MigrateSettingsCommand.php
packages/typo3-guides-cli/src/Migration/Dto/ProcessingResult.php
packages/typo3-guides-cli/src/Migration/Processor.php
packages/typo3-guides-cli/tests/unit/Command/MigrateSettingsCommandTest.php
packages/typo3-guides-cli/tests/unit/Migration/ProcessorTest.php

This produces better readable code and type safety.

[TASK] Return DTO instead of array as processing result of migration

---

packages/typo3-guides-cli/tests/unit/Repository/LegacySettingsRepositoryTest.php

This avoids deprecation messages about creation of dynamic property.

[BUGFIX] Declare property to LegacySettingsRepositoryTest

---

README.rst

This only creates the directory if it didn't exist and does not throw errors if it existed previously

[DOCS] Use mkdir -p

---

packages/typo3-guides-cli/src/Migration/Dto/MigrationResult.php
packages/typo3-guides-cli/src/Migration/Processor.php
packages/typo3-guides-cli/src/Migration/SettingsMigrator.php
packages/typo3-guides-cli/tests/unit/Migration/ProcessorTest.php
packages/typo3-guides-cli/tests/unit/Migration/SettingsMigratorTest.php

This produces better readable code.

[TASK] Return DTO instead of array as migration result

---

Documentation/Index.rst

Until the last update they caused neither warnings nor errors, so we didn't note them

[BUGFIX] Remove non-existant entries from docs menu

---

packages/typo3-docs-theme/resources/template/body/admonition.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/attention.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/default.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/important.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/note.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/seealso.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/tip.html.twig
packages/typo3-docs-theme/resources/template/body/admonitions/warning.html.twig
tests/Integration/tests/admonitions/expected/index.html
tests/Integration/tests/admonitions/input/index.rst

It is not really necessary to have separate templates for each admonition type.
Also fix Admonitions that are in one line. They had no content until now

[TASK] Clean up Admonition templates

---

Makefile

Currently, the guides.xml is not loaded, therefore the inventories are not resolved and there are warnings

[BUGFIX] Load guides.xml for make test-docs

---

Documentation/Index.rst
packages/typo3-docs-theme/composer.json
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/src/EventListeners/TestingModeActivator.php
packages/typo3-docs-theme/src/Renderer/DecoratingPlantumlRenderer.php
tests/ApplicationTestCase.php
tests/Integration/IntegrationTest.php
tests/Integration/tests/directive-uml/expected/index.html

When the docker container is used in testing pipelines
to test if documentation renders without warnings,
the plantuml server sometimes makes the tests fail by not being available.
This PR disables the plantuml server calls in testing-mode
that is when option --fail-on-log is set or in the integration tests

[BUGFIX] Deactivate PlantUmlServer calls for tests

---

packages/typo3-docs-theme/assets/sass/components/_images.scss
packages/typo3-docs-theme/assets/sass/theme.scss
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/body/figure.html.twig
tests/Integration/tests/images/Both-Folder-Image-Index/expected/Folder/index.html
tests/Integration/tests/images/No-Folders/expected/index.html
tests/Integration/tests/images/Only-Image-Folder/expected/index.html
tests/Integration/tests/images/Only-Index-Folder/expected/Folder/index.html

This restores the shadow, usefull for images who are white:
the shadow is applied if the image was defined with class "with-shadow":
```
..  image:: some-image.png
:class: with-shadow
```
Additionally restored styles for figures with and without shadows:
```
..  figure:: typo3-logo.svg
:class: with-shadow
Some Caption
..  figure:: typo3-logo.svg
Some Caption
```
resolves https://github.com/TYPO3-Documentation/render-guides/issues/289

[BUGFIX] Restore image shadows

---

packages/typo3-docs-theme/resources/template/structure/layout.html.twig
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/link-wizard/expected/index.html
tests/Integration/tests-full/menu-subpages-max-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html
tests/Integration/tests-full/menu-subpages/expected/index.html
tests/Integration/tests-full/meta-data/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/four.html
tests/Integration/tests-full/next-prev-by-toctree/expected/i.html
tests/Integration/tests-full/next-prev-by-toctree/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/one.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html
tests/Integration/tests-full/next-prev-by-toctree/expected/two.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

This attribute is usually set locally by color zilla in the browser. Someone must have copy-pasted it in the past. it can be safely removed.

[BUGFIX] Remove attribute cz-shortcut-listen from body

---

composer.lock
packages/typo3-docs-theme/resources/template/body/code.html.twig

Inline styles in code-block captions are supported now.
Trailing 0es in version numbers are no further dropped.
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/317

[TASK] Update to guides 3.3.3

---

packages/typo3-docs-theme/resources/template/structure/layoutParts/pageHeader.html.twig
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/link-wizard/expected/index.html
tests/Integration/tests-full/menu-subpages-max-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html
tests/Integration/tests-full/menu-subpages/expected/index.html
tests/Integration/tests-full/meta-data/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/four.html
tests/Integration/tests-full/next-prev-by-toctree/expected/i.html
tests/Integration/tests-full/next-prev-by-toctree/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/one.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html
tests/Integration/tests-full/next-prev-by-toctree/expected/two.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

It is intended to also provide the `role="search"` attribute: Not all assistive technologies may recognize the new HTML element by now.
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search
See: https://caniuse.com/mdn-html_elements_search
Related: #344

[TASK] Use search element

---

packages/typo3-docs-theme/assets/sass/components/_code.scss
packages/typo3-docs-theme/resources/public/css/theme.css

The font size of inline code (for example, `:file:`, `:php:`, etc) is too small in comparison with the surrounding text. It is now increased for better readability.

[TASK] Adjust font size of inline code

---

packages/typo3-docs-theme/assets/sass/components/_code.scss
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/body/code.html.twig
tests/Integration/tests/code-block/directive-only/expected/index.html
tests/Integration/tests/code-block/with-caption/expected/index.html
tests/Integration/tests/code-block/with-classes/expected/index.html
tests/Integration/tests/code-block/with-emphasize-lines/expected/index.html
tests/Integration/tests/code-block/with-language-aliases/expected/index.html
tests/Integration/tests/code-block/with-language-rst/expected/index.html
tests/Integration/tests/code-block/with-language-typoscript/expected/index.html
tests/Integration/tests/code-block/with-language/expected/index.html
tests/Integration/tests/code-block/with-line-number-start/expected/index.html
tests/Integration/tests/code-block/with-line-numbers/expected/index.html
tests/Integration/tests/configuration/expected/index.html
tests/Integration/tests/markdown/expected/README.html
tests/Integration/tests/tabs/expected/index.html

Previously, the copy button was just absolutely positioned at the end of the code block wrapper: Long code lines "run" into the button. Now, there are two distinct columns (brought by a newly introduced flexbox) which separate those two contents.
Resolves: #370

[BUGFIX] Avoid long code block lines run into copy button

---

packages/typo3-docs-theme/resources/template/structure/layoutParts/pageHeader.html.twig
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/link-wizard/expected/index.html
tests/Integration/tests-full/menu-subpages-max-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html
tests/Integration/tests-full/menu-subpages/expected/index.html
tests/Integration/tests-full/meta-data/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/four.html
tests/Integration/tests-full/next-prev-by-toctree/expected/i.html
tests/Integration/tests-full/next-prev-by-toctree/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/one.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html
tests/Integration/tests-full/next-prev-by-toctree/expected/two.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

[BUGFIX] Fix display of top search

---

packages/typo3-docs-theme/README.rst
packages/typo3-guides-cli/README.rst
packages/typo3-guides-extension/README.rst
packages/typo3-version-handling/README.rst

I noticed that the README.rst files for our subtree repositories are shown in the GitHub repositories, and do not properly indicate that those are subtree repos.
I tried to unify all four package READMEs, rather quick and dirty. Please check if this is suitable. Feel free to add commits to this branch to change wordings.

[TASK] Streamline documentation for subtree-split repositories

---

packages/typo3-version-handling/src/DefaultInventories.php
tests/Integration/tests/guides-inventories/expected/index.html

The `t3install` references the "Upgrade Guide" which is semantically wrong. Therefore, the `t3upgrade` key has been introduced.
As both are available in the wild, both are valid, but `t3install` should be considered legacy.

[TASK] Add "t3upgrade" key to the default inventories

---

packages/typo3-version-handling/src/DefaultInventories.php
tests/Integration/tests/guides-inventories/expected/index.html

It was missing until now and is one of the official contribution guides.

[TASK] Add writing guide to the default inventories

---

packages/typo3-docs-theme/assets/sass/_text.scss
packages/typo3-docs-theme/assets/sass/mixins/_focus.scss
packages/typo3-docs-theme/assets/sass/theme.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Hello,
this pull request add a **global behaviour for focus-visible** based on inner box-shadow. In that way, focus that are not yet handled in a specific way are always highlighted. The color is not set in purpose, in that way it will take the text color by default and then should always have a good contrast with the background.
Rachel

[Task] Styles focus

---

packages/typo3-docs-theme/assets/sass/_text.scss
packages/typo3-docs-theme/assets/sass/_variables.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Hello,
This one is focused on the **article text font size and styling**. 
Since the difference between the main menu and the article font sizes was considered too big, I have reduced the article font size from 1.2rem to 1.1rem. It is still confortable. 
Rachel

[Task] Styles article text

---

packages/typo3-version-handling/src/DefaultInventories.php

Fluid (the standalone API) does not belong to the core and does not support TYPO3 Versions.
Therefore currently interlinks to it fail when prefered version is not main.

[BUGFIX] Fix Fluid interlink

---

packages/typo3-docs-theme/resources/template/structure/document.html.twig
packages/typo3-docs-theme/resources/template/structure/navigation/meta-menu.html.twig
tests/Integration/tests-full/edit-on-github-directory/expected/Index.html
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/link-wizard/expected/index.html
tests/Integration/tests-full/menu-subpages-max-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html
tests/Integration/tests-full/menu-subpages/expected/index.html
tests/Integration/tests-full/meta-data/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/four.html
tests/Integration/tests-full/next-prev-by-toctree/expected/i.html
tests/Integration/tests-full/next-prev-by-toctree/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/one.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html
tests/Integration/tests-full/next-prev-by-toctree/expected/two.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

Adds a "Contributors Corner" to the mobile menu:
resolves https://github.com/TYPO3-Documentation/render-guides/issues/377

[FEATURE] Display source and GitHub link on mobile

---

Dockerfile

The Changelog rendering takes up a lot of memory, and thus cannot be done with the current 1G limit.
A change in guides:1.1.0 introduced caching, and that cache takes up a lot of space.
Native/local rendering often has no PHP memory limit set, so this may not apply to CI/development.

[BUGFIX] Raise docker memory limit to 4G

---

Documentation-rendertest/ThisAndThat/Index.rst

Even in sphinx it was deprecated

[TASK] Drop Centered directive from rendertest

---

composer.lock

- Upgrading phpdocumentor/guides (1.1.1 => 1.2.0): Extracting archive
- Upgrading phpdocumentor/guides-restructured-text (1.1.0 => 1.2.0): Extracting archive
The new directives do not work yet, seems like the templates are not loaded, will fix it in a follow-up.

[TASK] Update guides

---

Makefile

Currently `rendertest` uses the `t3docs:local` docker image, which first has to be built. But actually it can run with the normal `php` docker container, just like `make docs` does.
So this removes a dependeny on building a local docker image before and getting errors.
The same is applied to `make testdocs`, as this should also not require a local container beforehand.

[BUGFIX] Use simple PHP container for rendertest and test-docs

---

Documentation-rendertest/Confval/Index.rst

Use a directive with options as is done for sphinx: https://sphinx-toolbox.readthedocs.io/en/stable/extensions/confval.html#directive-option-confval-noindex
Demonstrate noindex and name options.
The style when options is used needs some overhaul, see #466
The permalink dialoge also needs to be adjusted for confvals with noindex option set: #467

[TASK] Overhaul the confval examples

---

packages/typo3-docs-theme/resources/template/body/directive/confval.html.twig
tests/Integration/tests/confval/confval-basic/expected/index.html
tests/Integration/tests/confval/confval-duplicate-with-name/expected/anotherDomain.html
tests/Integration/tests/confval/confval-duplicate-with-name/expected/index.html
tests/Integration/tests/confval/confval-duplicate/expected/anotherDomain.html
tests/Integration/tests/confval/confval-duplicate/expected/index.html

Style the options of the confval directive that are displayed as a fieldlist.
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/466
After: 
Before:

[BUGFIX] Adjust HTML of confval options

---

packages/typo3-docs-theme/assets/sass/_variables.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Hello,
This pull request changes globally in the css the variable $gray-800 from #666666 to #595959. 
It will be subtile and make all the dark grays (colors and backgrounds) a little bit darker. 
The real benefit is that it will give the overall documentation text a better contrast, (7.1) valid with WCAG AAA level.

[TASK] styles text contrast

---

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/src/TextRoles/SqlTextRole.php

We missed `:sql:` role handling to be specific, and receive a distinct popover.

[TASK] Add SQL popover highlighting

---

packages/typo3-docs-theme/resources/template/structure/layoutParts/footerAssets.html.twig
packages/typo3-docs-theme/src/Twig/TwigExtension.php
tests/Integration/tests-full/edit-on-github-directory/expected/Index.html
tests/Integration/tests-full/edit-on-github/expected/index.html
tests/Integration/tests-full/edit-on-github/expected/page1.html
tests/Integration/tests-full/edit-on-github/expected/subpages/index.html
tests/Integration/tests-full/index/expected/index.html
tests/Integration/tests-full/link-wizard/expected/index.html
tests/Integration/tests-full/menu-subpages-max-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-1/expected/index.html
tests/Integration/tests-full/menu-subpages-no-titlesonly-maxdepth-2/expected/index.html
tests/Integration/tests-full/menu-subpages/expected/index.html
tests/Integration/tests-full/meta-data/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/four.html
tests/Integration/tests-full/next-prev-by-toctree/expected/i.html
tests/Integration/tests-full/next-prev-by-toctree/expected/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/one.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/index.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/pi.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/three.html
tests/Integration/tests-full/next-prev-by-toctree/expected/three/threepointfive.html
tests/Integration/tests-full/next-prev-by-toctree/expected/two.html
tests/Integration/tests-full/next-prev/expected/index.html
tests/Integration/tests-full/next-prev/expected/page.html
tests/Integration/tests-full/next-prev/expected/yetAnotherPage.html
tests/Integration/tests-full/page-with-subpages/expected/index.html
tests/Integration/tests-full/page-with-subpages/expected/singlehtml/Index.html
tests/Integration/tests-full/page-with-subpages/expected/sub/index.html
tests/Integration/tests-full/two-toctrees/expected/index.html

Introduce a new Twig function "isRenderedForDeployment" that returns "true" when rendering is performed for upload to docs.typo3.org. In this case, URIs are generated with the "typo3.azureedge.net..." scope.
Only then, tracking javascript code will be emitted.
With local URIs in use, no tracking will be performed.
Fixes https://github.com/TYPO3-Documentation/render-guides/issues/378

[TASK] Disables tracking when locally rendered

---

packages/typo3-docs-theme/resources/template/body/directive/confval.html.twig
tests/Integration/tests/confval/confval-basic/expected/index.html
tests/Integration/tests/confval/confval-duplicate-with-name/expected/anotherDomain.html
tests/Integration/tests/confval/confval-duplicate-with-name/expected/index.html
tests/Integration/tests/confval/confval-duplicate/expected/anotherDomain.html
tests/Integration/tests/confval/confval-duplicate/expected/index.html

Resolves https://github.com/TYPO3-Documentation/render-guides/issues/479

[BUGFIX] Use anchor, not id for confval target

---

Documentation/Developer/InterlinkInventories.rst
packages/typo3-version-handling/src/DefaultInventories.php

Previously I could look into the settings.cfg to see keys and names of interlink inventories (because I do not know them all by heart), but now this is only available in the render-guides repository.
There seems to be a twig directive to get the enum values and their links, but I acutally need more:
* The name of the inventory as rendered for the Title
* The actual URL used
* The key of the inventory
So I made a manual list of this because I didn't want to enhance the ENUM to do too many things.
At least I need such a list, up to you if we want to maintain this in the docs this way, or if we would need a dynamic way...?!

[DOCS] Add list of inventories with descriptions

---

packages/typo3-docs-theme/assets/sass/components/_tabs.scss
packages/typo3-docs-theme/resources/public/css/theme.css

After:
Before:
resolves https://github.com/TYPO3-Documentation/render-guides/issues/419

[BUGFIX] Remove gab after tabs

---

Documentation-rendertest/Typesetting/Index.rst
packages/typo3-docs-theme/assets/sass/components/_code.scss
packages/typo3-docs-theme/resources/public/css/theme.css

After:
Before:
resolves https://github.com/TYPO3-Documentation/render-guides/issues/501

[BUGFIX] Fix code size in headers

---

packages/typo3-guides-extension/src/Command/RunDecorator.php

When the rendering gets performed without an input directory, "Documentation" is passed by default.
This means in a docker context, using this:
```
docker run --rm --pull always -v "$(shell pwd)":/project -t ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log --output-format=html
```
always needs to fixate the config directory, but does not explicitly specify `Documentation` as an input. This could be done with:
```
docker run --rm --pull always -v "$(shell pwd)":/project -t ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log --output-format=html Documentation
```
If that would be the case, all is good. A possible "Localization.ru_RU" directory would then be appended to the input, forming …

[BUGFIX] Fix automatic detection of input directory in localization mode

---

packages/typo3-docs-theme/assets/sass/components/_accordion.scss
packages/typo3-docs-theme/assets/sass/theme.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Hello,
this PR answer #512 issue.
Before:
After:

[TASK] Improve styles accordions

---

Documentation-rendertest/Directives/directoryTree.rst
packages/typo3-docs-theme/assets/sass/components/_directoryTree.scss
packages/typo3-docs-theme/assets/sass/theme.scss
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/body/directive/directory-tree.html.twig
packages/typo3-docs-theme/resources/template/inline/textroles/file.html.twig
packages/typo3-docs-theme/resources/template/inline/textroles/path.html.twig
packages/typo3-docs-theme/src/Directives/DirectoryTreeDirective.php
packages/typo3-docs-theme/src/Nodes/DirectoryTree/DirectoryTreeListItemNode.php
packages/typo3-docs-theme/src/Nodes/DirectoryTree/DirectoryTreeListNode.php
packages/typo3-docs-theme/src/Nodes/DirectoryTreeNode.php
tests/Integration/tests/directory-tree/expected/index.html
tests/Integration/tests/directory-tree/input/index.rst
tests/Integration/tests/file/expected/index.html
tests/Integration/tests/roles/role-file/expected/index.html

Introduce a collapsible directory tree:
There are advantages over using a plaintext codeblock like 
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Code/Codeblocks.html#show-a-directory-tree
In that the resulting tree is collapsible, takes up less space and is a native nested list which improves a11y.
Also it is much easier to use

[Feature] Introduce directory tree directive

---

Documentation-rendertest/Confval/Index.rst
composer.lock
packages/typo3-docs-theme/assets/sass/components/_table.scss
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig
packages/typo3-docs-theme/src/Compiler/NodeTransformers/ConfvalMenuNodeTransformer.php
packages/typo3-docs-theme/src/Directives/ConfvalMenuDirective.php
packages/typo3-docs-theme/src/Nodes/ConfvalMenuNode.php
tests/Integration/tests-full/navigation-title/expected/anotherPage.html
tests/Integration/tests-full/navigation-title/expected/index.html
tests/Integration/tests-full/navigation-title/expected/yetAnotherPage.html
tests/Integration/tests/confval/confval-basic/expected/index.html
tests/Integration/tests/confval/confval-duplicate-with-name/expected/anotherDomain.html
tests/Integration/tests/confval/confval-duplicate-with-name/expected/index.html
tests/Integration/tests/confval/confval-duplicate/expected/anotherDomain.html
tests/Integration/tests/confval/confval-duplicate/expected/index.html
tests/Integration/tests/confval/confval-menu-tree/expected/index.html
tests/Integration/tests/confval/confval-menu-tree/input/index.rst
tests/Integration/tests/confval/confval-noindex/expected/anotherDomain.html
tests/Integration/tests/confval/confval-noindex/expected/index.html

Displays all confvals of the current page as list, tree or table. Additional info can be displayed, confvals can be excluded. Recursively nested confvals are treated as tree.

[FEATURE] Introduce confval-menu directive

---

Documentation/Developer/Building.rst
Documentation/Installation/Index.rst
Documentation/Migration/Index.rst
Documentation/_Includes/NoteProjectDirectoryName.rst.txt
README.rst

People may think that "/project" is a directory they need to replace with the name of their project. Clarify this.
(Open for different wording)
Note: The README.rst.txt does not handle "include::" so instead I opted for a inline code note about "/project".

Clarify project

---

composer.json
composer.lock

This fixes a bug on case-insensitive file systems (macOS) for a mismatch of index.rst vs. Index.rst
see https://github.com/TYPO3-Documentation/t3docs-console-command/commit/59dd9e11948ee6f60cd4b6a9d09b331b32d2509f

[TASK] Raise t3docs/console-command dependency to 0.1.4

---

packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig
packages/typo3-docs-theme/src/Directives/ConfvalMenuDirective.php
tests/Integration/tests/confval/confval-menu-tree-anchor/expected/index.html
tests/Integration/tests/confval/confval-menu-tree-anchor/input/index.rst

This enables us to keep headlines in between with the rubric directive and to keep anchors functioning.

[TASK] Allow other nodes in confval menu

---

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/resources/template/inline/textroles/t3ext.html.twig
packages/typo3-docs-theme/resources/template/inline/textroles/t3src.html.twig
packages/typo3-docs-theme/src/TextRoles/T3extTextRole.php
packages/typo3-docs-theme/src/TextRoles/T3srcTextRole.php
tests/Integration/tests/roles/role-t3ext/expected/index.html
tests/Integration/tests/roles/role-t3ext/input/index.rst
tests/Integration/tests/roles/role-t3src-core-prefered/expected/index.html
tests/Integration/tests/roles/role-t3src/expected/index.html
tests/Integration/tests/roles/role-t3src/input/index.rst

Interpret the link/reference syntax where a custom link text can be given. Interpret more different input possibilities
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/609

[FEATURE] Improve t3src and t3ext textroles

---

composer.json
composer.lock

In the hope that this keeps dependabot from updating beyond PHP 8.1

[TASK] Set plattform requirements to PHP 8.1

---

packages/typo3-api/redirect.php
packages/typo3-api/template/components/class-title.html.twig

If you accidently stumbled on the Api page of a viewhelper (they are not very helpful) an info box with a link suggests you go to the reference instead:

[TASK] Suggest link to ViewHelper Reference

---

packages/typo3-docs-theme/src/Directives/ViewHelperDirective.php
tests/Integration/tests/viewhelper/expected/index.html
tests/Integration/tests/viewhelper/expected/objects.inv.json
tests/Integration/tests/viewhelper/input/index.rst

If option `:sortBy: name` or not sortBy is set, sort by name.
Otherwise the sorting from the json is preserved.
resolves https://github.com/TYPO3-Documentation/render-guides/issues/660

[FEATURE] Offer sorting options for viewhelper arguments

---

packages/typo3-docs-theme/src/TextRoles/FluidTextTextRole.php
packages/typo3-docs-theme/src/TextRoles/HtmlTextTextRole.php
packages/typo3-docs-theme/src/TextRoles/JavaScriptTextRole.php
packages/typo3-docs-theme/src/TextRoles/PhpTextRole.php
packages/typo3-docs-theme/src/TextRoles/RestructuredTextTextRole.php
packages/typo3-docs-theme/src/TextRoles/ShellTextTextRole.php
packages/typo3-docs-theme/src/TextRoles/SqlTextRole.php
packages/typo3-docs-theme/src/TextRoles/TSconfigTextRole.php
packages/typo3-docs-theme/src/TextRoles/TypeScriptTextRole.php
packages/typo3-docs-theme/src/TextRoles/TypoScriptTextTextRole.php
packages/typo3-docs-theme/src/TextRoles/XmlTextTextRole.php
packages/typo3-docs-theme/src/TextRoles/YamlTextTextRole.php
tests/Integration/tests-full/changelog/expected/Changelog/12.0/Breaking-87616-RemovedHookForAlteringPageLinks.html
tests/Integration/tests-full/edit-on-github/edit-on-github-per-page/expected/page1.html
tests/Integration/tests/code-inline/expected/index.html
tests/Integration/tests/code/code-php/expected/index.html
tests/Integration/tests/viewhelper/expected/index.html

As noted in https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/issues/243 this uses a more verbose
tooltip title for specifically highlighted code, see:

[TASK] Clarify TextRole popup titles

---

packages/typo3-docs-theme/assets/sass/components/_code.scss
packages/typo3-docs-theme/assets/sass/components/_table.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Resolves #564 
___
1. Image figure caption remains unchanged
2. Table caption gets the exact same styling as image caption
BEFORE:
AFTER:
3. Codeblocks caption gets the same styling as image caption, with additional border to contain caption within context
BEFORE:
AFTER:
4. Due to the change above, codeblocks without captions are also bordered to keep elements consistent
BEFORE:
AFTER:

[TASK] Unify caption styles for images, tables and codeblocks

---

packages/typo3-docs-theme/resources/template/structure/layoutParts/editOnGithubButtons.html.twig
packages/typo3-docs-theme/src/DependencyInjection/Typo3DocsThemeExtension.php
packages/typo3-docs-theme/src/Twig/TwigExtension.php
tests/Integration/tests-full/report-issue/project-issue-github/expected/index.html
tests/Integration/tests-full/report-issue/project-issue-github/input/guides.xml
tests/Integration/tests-full/report-issue/project-issue-github/input/index.rst
tests/Integration/tests-full/report-issue/project-issue-github/input/report.rst
tests/Integration/tests-full/report-issue/report-issue-forge/expected/index.html
tests/Integration/tests-full/report-issue/report-issue-forge/input/guides.xml
tests/Integration/tests-full/report-issue/report-issue-forge/input/index.rst
tests/Integration/tests-full/report-issue/report-issue-forge/input/report.rst
tests/Integration/tests-full/report-issue/report-issue-github/expected/index.html
tests/Integration/tests-full/report-issue/report-issue-github/input/guides.xml
tests/Integration/tests-full/report-issue/report-issue-github/input/index.rst
tests/Integration/tests-full/report-issue/report-issue-github/input/report.rst
tests/Integration/tests-full/report-issue/report-issue-internal/expected/index.html
tests/Integration/tests-full/report-issue/report-issue-internal/input/guides.xml
tests/Integration/tests-full/report-issue/report-issue-internal/input/index.rst
tests/Integration/tests-full/report-issue/report-issue-internal/input/report.rst
tests/Integration/tests/interlink/interlink-doc/expected/index.html
tests/Integration/tests/interlink/typo3_core_preferred/typo3_core_preferred_11.5/expected/index.html
tests/Integration/tests/interlink/typo3_core_preferred/typo3_core_preferred_default/expected/index.html
tests/Integration/tests/interlink/typo3_core_preferred/typo3_core_preferred_main/expected/index.html
tests/Integration/tests/interlink/typo3_core_preferred/typo3_core_preferred_stable/expected/index.html

Introduces a "Report issue" button:
Button is displayed if project-issues or report-issue are set in the guides.xml extension tag.
report-issue="none" disables the button while still displaying the issues link in the footer.
Links to Github and forge.typo3.org set some fields in the form like the title fields or the version field on forge.
Resolves: https://github.com/TYPO3-Documentation/render-guides/issues/673

[TASK] Introduce report issue button

---

Documentation-rendertest/Api/Index.rst
composer.lock
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/src/TextRoles/ApiClassTextRole.php
packages/typo3-version-handling/src/DefaultInventories.php
tests/Integration/tests/guides-inventories/expected/index.html

With this change you can link to any class etc on the phpapi:
```
*   :api-class:`\TYPO3\CMS\Extbase\Routing\ExtbasePluginEnhancer`
*   :api-class:`In main <api-dev:\TYPO3\CMS\Extbase\Routing\ExtbasePluginEnhancer>`
*   :api-class:`In 11.5 <api-11:\TYPO3\CMS\Extbase\Routing\ExtbasePluginEnhancer>
*   :api-class:`\TYPO3\CMS\Core\EventDispatcher\EventDispatcher <api:\TYPO3\CMS\Core\EventDispatcher\EventDispatcher>`
```

[FEATURE] Link to the TYPO3 API

---

packages/typo3-api/template/api-info.json.twig
packages/typo3-api/template/template.xml

Outputs information about all classes/interfaces in the TYPO3 Core in the following form, so that it can be consumed by the guides for help texts etc: 
```
"\\TYPO3\\CMS\\Adminpanel\\Log\\InMemoryLogWriter":  {
"url": "https://api.typo3.org/12.4/classes/TYPO3-CMS-Adminpanel-Log-InMemoryLogWriter.html",
"short": "InMemoryLogWriter",
"fqn": "\\TYPO3\\CMS\\Adminpanel\\Log\\InMemoryLogWriter",
"github": "https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/adminpanel/Classes/Log/InMemoryLogWriter.php",
"file": "typo3/sysext/adminpanel/Classes/Log/InMemoryLogWriter.php",
"type": "class",
"final": "1",
"abstract": "",
"readonly": "",
"internal": "1",
"internal-message": "",
"deprecated": "",
"deprecation": "",
"extends": "\\TYPO3\\CMS\\Core\\Log\\Writer\\AbstractWriter",
"implements": " …
```

[FEATURE] JSON with class/interface API information

---

Documentation-rendertest/PhpInline/Index.rst
packages/typo3-docs-theme/assets/sass/components/_code.scss
packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/inline/textroles/code.html.twig
packages/typo3-docs-theme/src/Api/Typo3ApiService.php
packages/typo3-docs-theme/src/Nodes/Inline/CodeInlineNode.php
packages/typo3-docs-theme/src/TextRoles/PhpTextRole.php
tests/Integration/tests-full/changelog/expected/Changelog/12.0/Breaking-87616-RemovedHookForAlteringPageLinks.html
tests/Integration/tests-full/edit-on-github/edit-on-github-per-page/expected/page1.html
tests/Integration/tests/code-inline/expected/index.html
tests/Integration/tests/code/code-php/expected/index.html
tests/Integration/tests/viewhelper/expected/index.html

Short view is opt-in and can for example be used if the same class is mentioned several times in the same context:
```
:php-short:`\TYPO3\CMS\Adminpanel\ModuleApi\ContentProviderInterface``
``

[FEATURE] Help texts for inline PHP code snippets

---

packages/typo3-docs-theme/assets/sass/components/_code.scss
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/inline/textroles/code.html.twig
tests/Integration/tests-full/changelog/expected/Changelog/12.0/Breaking-87616-RemovedHookForAlteringPageLinks.html
tests/Integration/tests-full/edit-on-github/edit-on-github-per-page/expected/page1.html
tests/Integration/tests/code-inline/expected/index.html
tests/Integration/tests/code/code-php/expected/index.html
tests/Integration/tests/viewhelper/expected/index.html

By only breaking inline-code longer than
10 chars we prevent very short code like "string" to break when used in tables or other tight spaces.

[BUGFIX] Do not break short inline code

---

packages/typo3-docs-theme/src/Directives/SiteSetSettingsDirective.php
tests/Integration/tests/roles/role-composer/expected/index.html
tests/Integration/tests/site-set-ext-syntax/_root_include/settings.definitions.yaml
tests/Integration/tests/site-set-ext-syntax/expected/index.html
tests/Integration/tests/site-set-ext-syntax/input/index.rst
tests/Integration/tests/site-set-failure/expected/index.html
tests/Integration/tests/site-set-failure/expected/logs/error.log
tests/Integration/tests/site-set-failure/expected/logs/warning.log
tests/Integration/tests/site-set-failure/input/index.rst

By default only files within a "Documentation/" directory can be read by the "typo3:site-set-settings" directive.
However in cases where extensions (Core or third party) provide additional files in their main directory, these should be accessible, to allow reading the ACTUAL file contents, and not requiring a copy to be placed inside Documentation/.
With this patch, a new syntax "EXT:self" allows to refer to this base "/project/" directory as a path prefix, instead of "/project/Documentation/". Other file traversal beyond this is forbidden.

[FEATURE] Allow "EXT:self" syntax for typo3:site-set-settings

---

Documentation-rendertest/ImagesAndFigures/Index.rst
packages/typo3-docs-theme/assets/sass/components/_images.scss
packages/typo3-docs-theme/assets/sass/components/directives/_versionchanged.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Especially in the context of lists, where last paragraphs miss the margin
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/703
After:

[BUGIFIX] Improve margins before and after images and admonitions

---

packages/typo3-docs-theme/assets/sass/components/directives/_confval.scss
packages/typo3-docs-theme/resources/public/css/theme.css

Fixes #698
This rather simple fix makes confval titles break preferably by white space, if there is no white space present or word is too long it will break anywhere.
BEFORE:
AFTER:
Note: Non-alphanumeric signs like dots or dashes are not taken into account when wrapping - in order to break titles by them, it would be necessary to parse the title beforehand to insert the [Line Break Opportunity `<wbr>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) when needed (e.g. before a dot or a dash), like so:
```html
this.text.breaks.anywhere
this<wbr>.text<wbr>.breaks<wbr>.on<wbr>.dots
```
Here is the preview for titles using the `<wbr>` tags (inserted manually):
```html
email<wbr>.templateRootPaths
expose<wbr>Nonexistent<wbr>User<wbr>In<wbr>Forgot<wbr>Password<wbr>Dialog
```

[BUGFIX] Fix word wrapping for long confval titles

---

Documentation-rendertest/SiteSettings/Index.rst
Documentation-rendertest/SiteSettings/_siteSetSettings.rst.txt
Documentation-rendertest/SiteSettings/settings.definitions.yaml
packages/typo3-docs-theme/assets/sass/components/_table.scss
packages/typo3-docs-theme/resources/public/css/theme.css
packages/typo3-docs-theme/resources/template/body/directive/confval-menu.html.twig

Generally allow word-breaks in table cells

[BUGFIX] Prevent duplicate escaping of abbreviated defaults

---

packages/typo3-docs-theme/src/Directives/SiteSetSettingsDirective.php
tests/Integration/tests/site-set-labels-autoload/expected/index.html
tests/Integration/tests/site-set-labels-autoload/input/_includes/Configuration/Sets/Felogin/config.yaml
tests/Integration/tests/site-set-labels-autoload/input/_includes/Configuration/Sets/Felogin/labels.xlf
tests/Integration/tests/site-set-labels-autoload/input/_includes/Configuration/Sets/Felogin/settings.definitions.yaml
tests/Integration/tests/site-set-labels-autoload/input/index.rst

The set language files introduced in https://forge.typo3.org/issues/104831 are now auto-loaded from labels.xlf within the sets folder, if the file is provided and the set configuration does not reference an explicit labels xlf file.

[TASK] Support auto-registration of set labels from labels.xlf

---

packages/typo3-docs-theme/resources/config/typo3-docs-theme.php
packages/typo3-docs-theme/src/Compiler/NodeTransformers/RemoveInterlinkSelfReferencesFromCrossReferenceNodeTransformer.php
tests/Integration/tests/interlink/interlink-self/expected/index.html
tests/Integration/tests/interlink/interlink-self/input/guides.xml
tests/Integration/tests/interlink/interlink-self/input/index.rst

If the interlink domain used in a reference is the same like the interlink_shortcode of the current document use internal references instead.
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/672

[BUGFIX] Prevent interlink from referencing itself

---

packages/typo3-api/template/css/custom.css.twig

This makes it clear that these two belong together
See https://github.com/TYPO3-Documentation/render-guides/blob/401acaf662d8fb6f6a833fc30cc89766567023cf/packages/typo3-docs-theme/assets/sass/layout/_structure.scss#L79

Reduce gap between argument signature and description

---

Makefile
packages/typo3-docs-theme/src/EventListeners/AddThemeSettingsToProjectNode.php
packages/typo3-guides-extension/src/Command/RunDecorator.php

This allows us to control specific settings needed for mininmal tests (like setting only a single output format) or more for the future.
Closes #764

[TASK] Add "--minimal-test" CLI option

---

entrypoint.sh

A common problem for macOS users running docker as non-root is that omitting a '--user' option makes our entrypoint.sh script try to on-the-fly create a matching user.
(See https://github.com/FriendsOfTYPO3/tea/issues/1490)
This patch adds a verbose error message to hint at the problem.

[TASK] Add verbose error when docker entrypoint fails

---

packages/typo3-docs-theme/assets/sass/_text.scss
packages/typo3-docs-theme/resources/public/css/theme.css

resolves #766 
Before: 
After:

Re-add color for second level list-points in a ordered list

---

Documentation-rendertest/Cards/Index.rst
Documentation/Developer/InterlinkInventories.rst
packages/typo3-version-handling/src/DefaultInventories.php
tests/Integration/tests/guides-inventories/expected/index.html

They are not available anymore for any supported TYPO3 version

[TASK] Delete removed guides from default inventories

---

.github/workflows/docker.yaml

The old @v3 version will be retired in December with two brownouts later in November.
This commits will:
* Make distinct unmutable digests during the artifact CREATION (prefixed "digests-linux-amd64", "digests-linux-arm-v7", "digests-linux-arm64") and upload them
* On the "merge" step, retrieve these digests and merge them into one single digest that is then used for the docker imagetools creation command.
Hat tips to Andreas Kienast and Stefan Bürk! :)

[TASK] Use GitHub actions/download-artifact@v4

---

packages/typo3-docs-theme/src/Twig/TwigExtension.php

This  fixes the edit button on the  documentation pages for markdown documents

[FIX] use source file to render editlink

---

packages/typo3-version-handling/src/Typo3VersionMapping.php

When a new TYPO3 release is made and the order of stable->oldstable changes by one version, the permalink tool offered via interecept (https://docs.typo3.org/permalink/xxx:yyy@zzz) must be updated, too.

[TASK] Add TODO hint to update intercept when changing versions

---

Documentation/Developer/Building.rst
tests/Integration/tests-full/external-menu/expected/index.html

[TASK] Follow-up: CDN change to cdn.typo3.com

---

packages/typo3-docs-theme/resources/template/body/directive/viewhelper/viewhelper-source.html.twig
tests/Integration/tests/viewhelper/viewhelper-all/expected/index.html

It causes errors as it is not in a section etc

[TASK] Remove the ViewHelper Source headline

---

.github/workflows/docker.yaml

AMD64 is the most supported cpu architecture, and ARM64 is used in modern apple laptops and some other devices. 
armv7 is not supported by the major platforms as this is an old 32 bit cpu. I think nobody is actually using this.

Remove docker armv7 build

---

.dockerignore
Dockerfile
entrypoint.sh
packages/typo3-guides-cli/bin/typo3-guides
packages/typo3-guides-cli/src/Command/CreateRedirectsFromGitCommand.php
packages/typo3-guides-cli/src/Git/GitChangeDetector.php
packages/typo3-guides-cli/src/Redirect/RedirectCreator.php

This is a prove of concept PR, showcasing how we could possibly generate a list of redirects. This is not complete and should be evaluated carefully. 
The purpose of the new command is to be able to automatically create directs for file that have been removed. For now we only use the git history, but we might want to expand this. For example to use the perma links used within most documentation.
To test this command you have to build the docker file for your local development. Using `make docker-build` .
After that the command can be tested on you local machine. 
```
docker run -i --rm --user 1000 -v${PWD}:/project typo3-docs:local create-redirects-from-git -b 3eb3cfc
```
Where `3eb3cfc` is a short sha of the project you are processing. In my example I used: …

[FEAT] Redirect generator based on git changes.
